context("Check for classes")

test_that("Existence check for all classes corresponding to each protobuf model", {
  expect_true(isClass(factset.protobuf.stach.Package))
  expect_true(isClass(factset.protobuf.stach.RowOrganizedPackage))
  expect_true(isClass(factset.protobuf.stach.table.CellDefinition))
  expect_true(isClass(factset.protobuf.stach.table.ColumnData))
  expect_true(isClass(factset.protobuf.stach.table.ColumnDefinition))
  expect_true(isClass(factset.protobuf.stach.table.DataFormat))
  expect_true(isClass(factset.protobuf.stach.table.HorizontalAlignment))
  expect_true(isClass(factset.protobuf.stach.table.ListOfMetadata))
  expect_true(isClass(factset.protobuf.stach.table.MetadataCollection))
  expect_true(isClass(factset.protobuf.stach.table.MetadataItem))
  expect_true(isClass(factset.protobuf.stach.table.MetadataLocations))
  expect_true(isClass(factset.protobuf.stach.table.Reference))
  expect_true(isClass(factset.protobuf.stach.table.ReferenceType))
  expect_true(isClass(factset.protobuf.stach.table.RowDefinition))
  expect_true(isClass(factset.protobuf.stach.table.Table))
  expect_true(isClass(factset.protobuf.stach.table.TableData))
  expect_true(isClass(factset.protobuf.stach.table.TableDefinition))
  expect_true(isClass(factset.protobuf.stach.table.VerticalAlignment))
})