// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/v2/table/DataFormat.proto

package com.factset.protobuf.stach.v2.table;

public final class DataFormatProto {
  private DataFormatProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFormatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factset.protobuf.stach.v2.table.DataFormat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The format
     * </pre>
     *
     * <code>string format = 1;</code>
     * @return The format.
     */
    java.lang.String getFormat();
    /**
     * <pre>
     * The format
     * </pre>
     *
     * <code>string format = 1;</code>
     * @return The bytes for format.
     */
    com.google.protobuf.ByteString
        getFormatBytes();

    /**
     * <pre>
     * The null format
     * </pre>
     *
     * <code>string null_format = 2;</code>
     * @return The nullFormat.
     */
    java.lang.String getNullFormat();
    /**
     * <pre>
     * The null format
     * </pre>
     *
     * <code>string null_format = 2;</code>
     * @return The bytes for nullFormat.
     */
    com.google.protobuf.ByteString
        getNullFormatBytes();

    /**
     * <pre>
     * The horizontal alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
     * @return The enum numeric value on the wire for halign.
     */
    int getHalignValue();
    /**
     * <pre>
     * The horizontal alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
     * @return The halign.
     */
    com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment getHalign();

    /**
     * <pre>
     * The vertical alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
     * @return The enum numeric value on the wire for valign.
     */
    int getValignValue();
    /**
     * <pre>
     * The vertical alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
     * @return The valign.
     */
    com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment getValign();
  }
  /**
   * <pre>
   * A data format
   * </pre>
   *
   * Protobuf type {@code factset.protobuf.stach.v2.table.DataFormat}
   */
  public static final class DataFormat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:factset.protobuf.stach.v2.table.DataFormat)
      DataFormatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFormat.newBuilder() to construct.
    private DataFormat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFormat() {
      format_ = "";
      nullFormat_ = "";
      halign_ = 0;
      valign_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DataFormat();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFormat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              format_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nullFormat_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              halign_ = rawValue;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              valign_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.factset.protobuf.stach.v2.table.DataFormatProto.internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.factset.protobuf.stach.v2.table.DataFormatProto.internal_static_factset_protobuf_stach_v2_table_DataFormat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.class, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder.class);
    }

    public static final int FORMAT_FIELD_NUMBER = 1;
    private volatile java.lang.Object format_;
    /**
     * <pre>
     * The format
     * </pre>
     *
     * <code>string format = 1;</code>
     * @return The format.
     */
    @java.lang.Override
    public java.lang.String getFormat() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        format_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The format
     * </pre>
     *
     * <code>string format = 1;</code>
     * @return The bytes for format.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFormatBytes() {
      java.lang.Object ref = format_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        format_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NULL_FORMAT_FIELD_NUMBER = 2;
    private volatile java.lang.Object nullFormat_;
    /**
     * <pre>
     * The null format
     * </pre>
     *
     * <code>string null_format = 2;</code>
     * @return The nullFormat.
     */
    @java.lang.Override
    public java.lang.String getNullFormat() {
      java.lang.Object ref = nullFormat_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nullFormat_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The null format
     * </pre>
     *
     * <code>string null_format = 2;</code>
     * @return The bytes for nullFormat.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNullFormatBytes() {
      java.lang.Object ref = nullFormat_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nullFormat_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HALIGN_FIELD_NUMBER = 3;
    private int halign_;
    /**
     * <pre>
     * The horizontal alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
     * @return The enum numeric value on the wire for halign.
     */
    @java.lang.Override public int getHalignValue() {
      return halign_;
    }
    /**
     * <pre>
     * The horizontal alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
     * @return The halign.
     */
    @java.lang.Override public com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment getHalign() {
      @SuppressWarnings("deprecation")
      com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment result = com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.valueOf(halign_);
      return result == null ? com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.UNRECOGNIZED : result;
    }

    public static final int VALIGN_FIELD_NUMBER = 4;
    private int valign_;
    /**
     * <pre>
     * The vertical alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
     * @return The enum numeric value on the wire for valign.
     */
    @java.lang.Override public int getValignValue() {
      return valign_;
    }
    /**
     * <pre>
     * The vertical alignment
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
     * @return The valign.
     */
    @java.lang.Override public com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment getValign() {
      @SuppressWarnings("deprecation")
      com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment result = com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.valueOf(valign_);
      return result == null ? com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getFormatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, format_);
      }
      if (!getNullFormatBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nullFormat_);
      }
      if (halign_ != com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.UNKNOWN_HALIGN.getNumber()) {
        output.writeEnum(3, halign_);
      }
      if (valign_ != com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.UNKNOWN_VALIGN.getNumber()) {
        output.writeEnum(4, valign_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getFormatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, format_);
      }
      if (!getNullFormatBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nullFormat_);
      }
      if (halign_ != com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.UNKNOWN_HALIGN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, halign_);
      }
      if (valign_ != com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.UNKNOWN_VALIGN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, valign_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat)) {
        return super.equals(obj);
      }
      com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat other = (com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat) obj;

      if (!getFormat()
          .equals(other.getFormat())) return false;
      if (!getNullFormat()
          .equals(other.getNullFormat())) return false;
      if (halign_ != other.halign_) return false;
      if (valign_ != other.valign_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getFormat().hashCode();
      hash = (37 * hash) + NULL_FORMAT_FIELD_NUMBER;
      hash = (53 * hash) + getNullFormat().hashCode();
      hash = (37 * hash) + HALIGN_FIELD_NUMBER;
      hash = (53 * hash) + halign_;
      hash = (37 * hash) + VALIGN_FIELD_NUMBER;
      hash = (53 * hash) + valign_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A data format
     * </pre>
     *
     * Protobuf type {@code factset.protobuf.stach.v2.table.DataFormat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factset.protobuf.stach.v2.table.DataFormat)
        com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.factset.protobuf.stach.v2.table.DataFormatProto.internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.factset.protobuf.stach.v2.table.DataFormatProto.internal_static_factset_protobuf_stach_v2_table_DataFormat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.class, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder.class);
      }

      // Construct using com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        format_ = "";

        nullFormat_ = "";

        halign_ = 0;

        valign_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.factset.protobuf.stach.v2.table.DataFormatProto.internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getDefaultInstanceForType() {
        return com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance();
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat build() {
        com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat buildPartial() {
        com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat result = new com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat(this);
        result.format_ = format_;
        result.nullFormat_ = nullFormat_;
        result.halign_ = halign_;
        result.valign_ = valign_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat) {
          return mergeFrom((com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat other) {
        if (other == com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance()) return this;
        if (!other.getFormat().isEmpty()) {
          format_ = other.format_;
          onChanged();
        }
        if (!other.getNullFormat().isEmpty()) {
          nullFormat_ = other.nullFormat_;
          onChanged();
        }
        if (other.halign_ != 0) {
          setHalignValue(other.getHalignValue());
        }
        if (other.valign_ != 0) {
          setValignValue(other.getValignValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object format_ = "";
      /**
       * <pre>
       * The format
       * </pre>
       *
       * <code>string format = 1;</code>
       * @return The format.
       */
      public java.lang.String getFormat() {
        java.lang.Object ref = format_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          format_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The format
       * </pre>
       *
       * <code>string format = 1;</code>
       * @return The bytes for format.
       */
      public com.google.protobuf.ByteString
          getFormatBytes() {
        java.lang.Object ref = format_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          format_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The format
       * </pre>
       *
       * <code>string format = 1;</code>
       * @param value The format to set.
       * @return This builder for chaining.
       */
      public Builder setFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        format_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The format
       * </pre>
       *
       * <code>string format = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFormat() {
        
        format_ = getDefaultInstance().getFormat();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The format
       * </pre>
       *
       * <code>string format = 1;</code>
       * @param value The bytes for format to set.
       * @return This builder for chaining.
       */
      public Builder setFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        format_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nullFormat_ = "";
      /**
       * <pre>
       * The null format
       * </pre>
       *
       * <code>string null_format = 2;</code>
       * @return The nullFormat.
       */
      public java.lang.String getNullFormat() {
        java.lang.Object ref = nullFormat_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nullFormat_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The null format
       * </pre>
       *
       * <code>string null_format = 2;</code>
       * @return The bytes for nullFormat.
       */
      public com.google.protobuf.ByteString
          getNullFormatBytes() {
        java.lang.Object ref = nullFormat_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nullFormat_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The null format
       * </pre>
       *
       * <code>string null_format = 2;</code>
       * @param value The nullFormat to set.
       * @return This builder for chaining.
       */
      public Builder setNullFormat(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nullFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The null format
       * </pre>
       *
       * <code>string null_format = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNullFormat() {
        
        nullFormat_ = getDefaultInstance().getNullFormat();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The null format
       * </pre>
       *
       * <code>string null_format = 2;</code>
       * @param value The bytes for nullFormat to set.
       * @return This builder for chaining.
       */
      public Builder setNullFormatBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nullFormat_ = value;
        onChanged();
        return this;
      }

      private int halign_ = 0;
      /**
       * <pre>
       * The horizontal alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
       * @return The enum numeric value on the wire for halign.
       */
      @java.lang.Override public int getHalignValue() {
        return halign_;
      }
      /**
       * <pre>
       * The horizontal alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
       * @param value The enum numeric value on the wire for halign to set.
       * @return This builder for chaining.
       */
      public Builder setHalignValue(int value) {
        
        halign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The horizontal alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
       * @return The halign.
       */
      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment getHalign() {
        @SuppressWarnings("deprecation")
        com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment result = com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.valueOf(halign_);
        return result == null ? com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The horizontal alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
       * @param value The halign to set.
       * @return This builder for chaining.
       */
      public Builder setHalign(com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.HorizontalAlignment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        halign_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The horizontal alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.HorizontalAlignment halign = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHalign() {
        
        halign_ = 0;
        onChanged();
        return this;
      }

      private int valign_ = 0;
      /**
       * <pre>
       * The vertical alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
       * @return The enum numeric value on the wire for valign.
       */
      @java.lang.Override public int getValignValue() {
        return valign_;
      }
      /**
       * <pre>
       * The vertical alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
       * @param value The enum numeric value on the wire for valign to set.
       * @return This builder for chaining.
       */
      public Builder setValignValue(int value) {
        
        valign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The vertical alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
       * @return The valign.
       */
      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment getValign() {
        @SuppressWarnings("deprecation")
        com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment result = com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.valueOf(valign_);
        return result == null ? com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * The vertical alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
       * @param value The valign to set.
       * @return This builder for chaining.
       */
      public Builder setValign(com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.VerticalAlignment value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        valign_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The vertical alignment
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.VerticalAlignment valign = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearValign() {
        
        valign_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:factset.protobuf.stach.v2.table.DataFormat)
    }

    // @@protoc_insertion_point(class_scope:factset.protobuf.stach.v2.table.DataFormat)
    private static final com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat();
    }

    public static com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFormat>
        PARSER = new com.google.protobuf.AbstractParser<DataFormat>() {
      @java.lang.Override
      public DataFormat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFormat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFormat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFormat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_v2_table_DataFormat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,fds/protobuf/stach/v2/table/DataFormat" +
      ".proto\022\037factset.protobuf.stach.v2.table\032" +
      "5fds/protobuf/stach/v2/table/HorizontalA" +
      "lignment.proto\0323fds/protobuf/stach/v2/ta" +
      "ble/VerticalAlignment.proto\"\273\001\n\nDataForm" +
      "at\022\016\n\006format\030\001 \001(\t\022\023\n\013null_format\030\002 \001(\t\022" +
      "D\n\006halign\030\003 \001(\01624.factset.protobuf.stach" +
      ".v2.table.HorizontalAlignment\022B\n\006valign\030" +
      "\004 \001(\01622.factset.protobuf.stach.v2.table." +
      "VerticalAlignmentB\234\001\n#com.factset.protob" +
      "uf.stach.v2.tableB\017DataFormatProtoZBgith" +
      "ub.com/factset/stachschema-sdks/go/fds/p" +
      "rotobuf/stach/v2/table\252\002\037FactSet.Protobu" +
      "f.Stach.V2.Tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.getDescriptor(),
          com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.getDescriptor(),
        });
    internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factset_protobuf_stach_v2_table_DataFormat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_v2_table_DataFormat_descriptor,
        new java.lang.String[] { "Format", "NullFormat", "Halign", "Valign", });
    com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.getDescriptor();
    com.factset.protobuf.stach.v2.table.VerticalAlignmentProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
