version: '3'
services:
  generate_dotnet:
    build:
      context: .
      dockerfile: dotnet/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./dotnet:/dotnet
  generate_js:
    build:
      context: .
      dockerfile: js/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./js:/js
  generate_python:
    build:
      context: .
      dockerfile: python/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./python:/python
  generate_java:
    build:
      context: .
      dockerfile: java/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./java:/java
  generate_r:
    build:
      context: .
      dockerfile: r/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./r:/r
  generate_go:
    build:
      context: .
      dockerfile: go/Dockerfile.generate
    volumes:
    - ${SCHEMA}:/schema
    - ./go:/golang