// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.20.1
// source: fds/protobuf/stach/v3/Views.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//
//A set of a metadata specifying one or more views for rendering a table.
type Views struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//The views.
	//The first view is considered the default view when rendering the table.
	//Required.
	Views []*Views_View `protobuf:"bytes,1,rep,name=views,proto3" json:"views,omitempty"`
}

func (x *Views) Reset() {
	*x = Views{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fds_protobuf_stach_v3_Views_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Views) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Views) ProtoMessage() {}

func (x *Views) ProtoReflect() protoreflect.Message {
	mi := &file_fds_protobuf_stach_v3_Views_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Views.ProtoReflect.Descriptor instead.
func (*Views) Descriptor() ([]byte, []int) {
	return file_fds_protobuf_stach_v3_Views_proto_rawDescGZIP(), []int{0}
}

func (x *Views) GetViews() []*Views_View {
	if x != nil {
		return x.Views
	}
	return nil
}

//
//A view for rendering a table.
type Views_View struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//
	//The name of the view.
	//Required.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//
	//The display name that describes the type of view.
	//This is used when presenting the user with a list of views that can be rendered. e.g. 'Table', 'Bubble Chart', etc.
	//Optional.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	//
	//The type of view to render the table.
	//Required.
	//
	// Types that are assignable to Type:
	//	*Views_View_Table
	Type isViews_View_Type `protobuf_oneof:"type"`
}

func (x *Views_View) Reset() {
	*x = Views_View{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fds_protobuf_stach_v3_Views_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Views_View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Views_View) ProtoMessage() {}

func (x *Views_View) ProtoReflect() protoreflect.Message {
	mi := &file_fds_protobuf_stach_v3_Views_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Views_View.ProtoReflect.Descriptor instead.
func (*Views_View) Descriptor() ([]byte, []int) {
	return file_fds_protobuf_stach_v3_Views_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Views_View) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Views_View) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (m *Views_View) GetType() isViews_View_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Views_View) GetTable() *TableView {
	if x, ok := x.GetType().(*Views_View_Table); ok {
		return x.Table
	}
	return nil
}

type isViews_View_Type interface {
	isViews_View_Type()
}

type Views_View_Table struct {
	//
	//The instructions to render tabular data into a rendered table.
	Table *TableView `protobuf:"bytes,3,opt,name=table,proto3,oneof"`
}

func (*Views_View_Table) isViews_View_Type() {}

var File_fds_protobuf_stach_v3_Views_proto protoreflect.FileDescriptor

var file_fds_protobuf_stach_v3_Views_proto_rawDesc = []byte{
	0x0a, 0x21, 0x66, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73,
	0x74, 0x61, 0x63, 0x68, 0x2f, 0x76, 0x33, 0x2f, 0x56, 0x69, 0x65, 0x77, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x19, 0x66, 0x61, 0x63, 0x74, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x61, 0x63, 0x68, 0x2e, 0x76, 0x33, 0x1a, 0x25,
	0x66, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x61,
	0x63, 0x68, 0x2f, 0x76, 0x33, 0x2f, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x69, 0x65, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xca, 0x01, 0x0a, 0x05, 0x56, 0x69, 0x65, 0x77, 0x73, 0x12,
	0x3b, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25,
	0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x73, 0x74, 0x61, 0x63, 0x68, 0x2e, 0x76, 0x33, 0x2e, 0x56, 0x69, 0x65, 0x77, 0x73,
	0x2e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x1a, 0x83, 0x01, 0x0a,
	0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x05,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73,
	0x74, 0x61, 0x63, 0x68, 0x2e, 0x76, 0x33, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x69, 0x65,
	0x77, 0x48, 0x00, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x85, 0x01, 0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x74, 0x61, 0x63,
	0x68, 0x2e, 0x76, 0x33, 0x42, 0x0a, 0x56, 0x69, 0x65, 0x77, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x66, 0x61, 0x63,
	0x74, 0x73, 0x65, 0x74, 0x2f, 0x73, 0x74, 0x61, 0x63, 0x68, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x2d, 0x73, 0x64, 0x6b, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x66, 0x64, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x61, 0x63, 0x68, 0x2f, 0x76, 0x33, 0xaa, 0x02,
	0x19, 0x46, 0x61, 0x63, 0x74, 0x53, 0x65, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x61, 0x63, 0x68, 0x2e, 0x56, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_fds_protobuf_stach_v3_Views_proto_rawDescOnce sync.Once
	file_fds_protobuf_stach_v3_Views_proto_rawDescData = file_fds_protobuf_stach_v3_Views_proto_rawDesc
)

func file_fds_protobuf_stach_v3_Views_proto_rawDescGZIP() []byte {
	file_fds_protobuf_stach_v3_Views_proto_rawDescOnce.Do(func() {
		file_fds_protobuf_stach_v3_Views_proto_rawDescData = protoimpl.X.CompressGZIP(file_fds_protobuf_stach_v3_Views_proto_rawDescData)
	})
	return file_fds_protobuf_stach_v3_Views_proto_rawDescData
}

var file_fds_protobuf_stach_v3_Views_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fds_protobuf_stach_v3_Views_proto_goTypes = []interface{}{
	(*Views)(nil),      // 0: factset.protobuf.stach.v3.Views
	(*Views_View)(nil), // 1: factset.protobuf.stach.v3.Views.View
	(*TableView)(nil),  // 2: factset.protobuf.stach.v3.TableView
}
var file_fds_protobuf_stach_v3_Views_proto_depIdxs = []int32{
	1, // 0: factset.protobuf.stach.v3.Views.views:type_name -> factset.protobuf.stach.v3.Views.View
	2, // 1: factset.protobuf.stach.v3.Views.View.table:type_name -> factset.protobuf.stach.v3.TableView
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fds_protobuf_stach_v3_Views_proto_init() }
func file_fds_protobuf_stach_v3_Views_proto_init() {
	if File_fds_protobuf_stach_v3_Views_proto != nil {
		return
	}
	file_fds_protobuf_stach_v3_TableView_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_fds_protobuf_stach_v3_Views_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Views); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fds_protobuf_stach_v3_Views_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Views_View); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_fds_protobuf_stach_v3_Views_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Views_View_Table)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fds_protobuf_stach_v3_Views_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fds_protobuf_stach_v3_Views_proto_goTypes,
		DependencyIndexes: file_fds_protobuf_stach_v3_Views_proto_depIdxs,
		MessageInfos:      file_fds_protobuf_stach_v3_Views_proto_msgTypes,
	}.Build()
	File_fds_protobuf_stach_v3_Views_proto = out.File
	file_fds_protobuf_stach_v3_Views_proto_rawDesc = nil
	file_fds_protobuf_stach_v3_Views_proto_goTypes = nil
	file_fds_protobuf_stach_v3_Views_proto_depIdxs = nil
}
