# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/v3/Column.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.v3 import MetadataItem_pb2 as fds_dot_protobuf_dot_stach_dot_v3_dot_MetadataItem__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"fds/protobuf/stach/v3/Column.proto\x12\x19\x66\x61\x63tset.protobuf.stach.v3\x1a(fds/protobuf/stach/v3/MetadataItem.proto\"\xd1\x01\n\x06\x43olumn\x12\x17\n\x0f\x63ontextual_type\x18\x01 \x01(\t\x12N\n\x0f\x63ustom_metadata\x18\x64 \x03(\x0b\x32\x35.factset.protobuf.stach.v3.Column.CustomMetadataEntry\x1a^\n\x13\x43ustomMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.factset.protobuf.stach.v3.MetadataItem:\x02\x38\x01\x42\x86\x01\n\x1d\x63om.factset.protobuf.stach.v3B\x0b\x43olumnProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\xaa\x02\x19\x46\x61\x63tSet.Protobuf.Stach.V3b\x06proto3')



_COLUMN = DESCRIPTOR.message_types_by_name['Column']
_COLUMN_CUSTOMMETADATAENTRY = _COLUMN.nested_types_by_name['CustomMetadataEntry']
Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), {

  'CustomMetadataEntry' : _reflection.GeneratedProtocolMessageType('CustomMetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _COLUMN_CUSTOMMETADATAENTRY,
    '__module__' : 'fds.protobuf.stach.v3.Column_pb2'
    # @@protoc_insertion_point(class_scope:factset.protobuf.stach.v3.Column.CustomMetadataEntry)
    })
  ,
  'DESCRIPTOR' : _COLUMN,
  '__module__' : 'fds.protobuf.stach.v3.Column_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.v3.Column)
  })
_sym_db.RegisterMessage(Column)
_sym_db.RegisterMessage(Column.CustomMetadataEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.factset.protobuf.stach.v3B\013ColumnProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\252\002\031FactSet.Protobuf.Stach.V3'
  _COLUMN_CUSTOMMETADATAENTRY._options = None
  _COLUMN_CUSTOMMETADATAENTRY._serialized_options = b'8\001'
  _COLUMN._serialized_start=108
  _COLUMN._serialized_end=317
  _COLUMN_CUSTOMMETADATAENTRY._serialized_start=223
  _COLUMN_CUSTOMMETADATAENTRY._serialized_end=317
# @@protoc_insertion_point(module_scope)
