# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/v3/MetadataItem.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(fds/protobuf/stach/v3/MetadataItem.proto\x12\x19\x66\x61\x63tset.protobuf.stach.v3\x1a\x1cgoogle/protobuf/struct.proto\"N\n\x0cMetadataItem\x12\x17\n\x0f\x63ontextual_type\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.google.protobuf.ValueB\x8c\x01\n\x1d\x63om.factset.protobuf.stach.v3B\x11MetadataItemProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\xaa\x02\x19\x46\x61\x63tSet.Protobuf.Stach.V3b\x06proto3')



_METADATAITEM = DESCRIPTOR.message_types_by_name['MetadataItem']
MetadataItem = _reflection.GeneratedProtocolMessageType('MetadataItem', (_message.Message,), {
  'DESCRIPTOR' : _METADATAITEM,
  '__module__' : 'fds.protobuf.stach.v3.MetadataItem_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.v3.MetadataItem)
  })
_sym_db.RegisterMessage(MetadataItem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.factset.protobuf.stach.v3B\021MetadataItemProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\252\002\031FactSet.Protobuf.Stach.V3'
  _METADATAITEM._serialized_start=101
  _METADATAITEM._serialized_end=179
# @@protoc_insertion_point(module_scope)
