# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/v3/Views.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/v3/Views.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.v3 import TableView_pb2 as fds_dot_protobuf_dot_stach_dot_v3_dot_TableView__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!fds/protobuf/stach/v3/Views.proto\x12\x19\x66\x61\x63tset.protobuf.stach.v3\x1a%fds/protobuf/stach/v3/TableView.proto\"\xa8\x01\n\x05Views\x12\x34\n\x05views\x18\x01 \x03(\x0b\x32%.factset.protobuf.stach.v3.Views.View\x1ai\n\x04View\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\x35\n\x05table\x18\x03 \x01(\x0b\x32$.factset.protobuf.stach.v3.TableViewH\x00\x42\x06\n\x04typeB\x85\x01\n\x1d\x63om.factset.protobuf.stach.v3B\nViewsProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\xaa\x02\x19\x46\x61\x63tSet.Protobuf.Stach.V3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.v3.Views_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\035com.factset.protobuf.stach.v3B\nViewsProtoZ<github.com/factset/stachschema-sdks/go/fds/protobuf/stach/v3\252\002\031FactSet.Protobuf.Stach.V3'
  _globals['_VIEWS']._serialized_start=104
  _globals['_VIEWS']._serialized_end=272
  _globals['_VIEWS_VIEW']._serialized_start=167
  _globals['_VIEWS_VIEW']._serialized_end=272
# @@protoc_insertion_point(module_scope)
