# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/table/Reference.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/table/Reference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import ReferenceType_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_ReferenceType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(fds/protobuf/stach/table/Reference.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a,fds/protobuf/stach/table/ReferenceType.proto\"\x85\x01\n\tReference\x12\x43\n\x0ereference_type\x18\x01 \x01(\x0e\x32+.factset.protobuf.stach.table.ReferenceType\x12\x10\n\x08table_id\x18\x02 \x01(\t\x12\x11\n\tcolumn_id\x18\x03 \x01(\t\x12\x0e\n\x06row_id\x18\x04 \x01(\tBQ\n com.factset.protobuf.stach.tableB\x0eReferenceProto\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.table.Reference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.factset.protobuf.stach.tableB\016ReferenceProto\252\002\034FactSet.Protobuf.Stach.Table'
  _globals['_REFERENCE']._serialized_start=121
  _globals['_REFERENCE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
