# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/table/TableDefinition.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/table/TableDefinition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import SeriesDefinition_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_SeriesDefinition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.fds/protobuf/stach/table/TableDefinition.proto\x12\x1c\x66\x61\x63tset.protobuf.stach.table\x1a/fds/protobuf/stach/table/SeriesDefinition.proto\"k\n\x0fTableDefinition\x12\x17\n\x0fheader_table_id\x18\x01 \x01(\t\x12?\n\x07\x63olumns\x18\x02 \x03(\x0b\x32..factset.protobuf.stach.table.SeriesDefinitionBW\n com.factset.protobuf.stach.tableB\x14TableDefinitionProto\xaa\x02\x1c\x46\x61\x63tSet.Protobuf.Stach.Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.table.TableDefinition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n com.factset.protobuf.stach.tableB\024TableDefinitionProto\252\002\034FactSet.Protobuf.Stach.Table'
  _globals['_TABLEDEFINITION']._serialized_start=129
  _globals['_TABLEDEFINITION']._serialized_end=236
# @@protoc_insertion_point(module_scope)
