// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/v3/Column.proto

package com.factset.protobuf.stach.v3;

public final class ColumnProto {
  private ColumnProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ColumnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factset.protobuf.stach.v3.Column)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *The type that defines a higher level contextual type.
     *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
     *Required.
     * </pre>
     *
     * <code>string contextual_type = 1;</code>
     * @return The contextualType.
     */
    java.lang.String getContextualType();
    /**
     * <pre>
     *The type that defines a higher level contextual type.
     *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
     *Required.
     * </pre>
     *
     * <code>string contextual_type = 1;</code>
     * @return The bytes for contextualType.
     */
    com.google.protobuf.ByteString
        getContextualTypeBytes();

    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    int getCustomMetadataCount();
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    boolean containsCustomMetadata(
        java.lang.String key);
    /**
     * Use {@link #getCustomMetadataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
    getCustomMetadata();
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
    getCustomMetadataMap();
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */

    /* nullable */
com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem defaultValue);
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */

    com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   *A set of metadata for a table column.
   * </pre>
   *
   * Protobuf type {@code factset.protobuf.stach.v3.Column}
   */
  public static final class Column extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:factset.protobuf.stach.v3.Column)
      ColumnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Column.newBuilder() to construct.
    private Column(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Column() {
      contextualType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Column();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Column(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              contextualType_ = s;
              break;
            }
            case 802: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                customMetadata_ = com.google.protobuf.MapField.newMapField(
                    CustomMetadataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
              customMetadata__ = input.readMessage(
                  CustomMetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              customMetadata_.getMutableMap().put(
                  customMetadata__.getKey(), customMetadata__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 100:
          return internalGetCustomMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.factset.protobuf.stach.v3.ColumnProto.Column.class, com.factset.protobuf.stach.v3.ColumnProto.Column.Builder.class);
    }

    public static final int CONTEXTUAL_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object contextualType_;
    /**
     * <pre>
     *The type that defines a higher level contextual type.
     *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
     *Required.
     * </pre>
     *
     * <code>string contextual_type = 1;</code>
     * @return The contextualType.
     */
    @java.lang.Override
    public java.lang.String getContextualType() {
      java.lang.Object ref = contextualType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contextualType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *The type that defines a higher level contextual type.
     *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
     *Required.
     * </pre>
     *
     * <code>string contextual_type = 1;</code>
     * @return The bytes for contextualType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContextualTypeBytes() {
      java.lang.Object ref = contextualType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contextualType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CUSTOM_METADATA_FIELD_NUMBER = 100;
    private static final class CustomMetadataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>newDefaultInstance(
                  com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> customMetadata_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
    internalGetCustomMetadata() {
      if (customMetadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CustomMetadataDefaultEntryHolder.defaultEntry);
      }
      return customMetadata_;
    }

    public int getCustomMetadataCount() {
      return internalGetCustomMetadata().getMap().size();
    }
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */

    @java.lang.Override
    public boolean containsCustomMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetCustomMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCustomMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> getCustomMetadata() {
      return getCustomMetadataMap();
    }
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> getCustomMetadataMap() {
      return internalGetCustomMetadata().getMap();
    }
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    @java.lang.Override

    public com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrDefault(
        java.lang.String key,
        com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> map =
          internalGetCustomMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *The custom metadata.
     *Optional.
     * </pre>
     *
     * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
     */
    @java.lang.Override

    public com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> map =
          internalGetCustomMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contextualType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, contextualType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCustomMetadata(),
          CustomMetadataDefaultEntryHolder.defaultEntry,
          100);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(contextualType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, contextualType_);
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> entry
           : internalGetCustomMetadata().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
        customMetadata__ = CustomMetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(100, customMetadata__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.factset.protobuf.stach.v3.ColumnProto.Column)) {
        return super.equals(obj);
      }
      com.factset.protobuf.stach.v3.ColumnProto.Column other = (com.factset.protobuf.stach.v3.ColumnProto.Column) obj;

      if (!getContextualType()
          .equals(other.getContextualType())) return false;
      if (!internalGetCustomMetadata().equals(
          other.internalGetCustomMetadata())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTEXTUAL_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getContextualType().hashCode();
      if (!internalGetCustomMetadata().getMap().isEmpty()) {
        hash = (37 * hash) + CUSTOM_METADATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCustomMetadata().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v3.ColumnProto.Column parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.factset.protobuf.stach.v3.ColumnProto.Column prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *A set of metadata for a table column.
     * </pre>
     *
     * Protobuf type {@code factset.protobuf.stach.v3.Column}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factset.protobuf.stach.v3.Column)
        com.factset.protobuf.stach.v3.ColumnProto.ColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 100:
            return internalGetCustomMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 100:
            return internalGetMutableCustomMetadata();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.factset.protobuf.stach.v3.ColumnProto.Column.class, com.factset.protobuf.stach.v3.ColumnProto.Column.Builder.class);
      }

      // Construct using com.factset.protobuf.stach.v3.ColumnProto.Column.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        contextualType_ = "";

        internalGetMutableCustomMetadata().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.factset.protobuf.stach.v3.ColumnProto.internal_static_factset_protobuf_stach_v3_Column_descriptor;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v3.ColumnProto.Column getDefaultInstanceForType() {
        return com.factset.protobuf.stach.v3.ColumnProto.Column.getDefaultInstance();
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v3.ColumnProto.Column build() {
        com.factset.protobuf.stach.v3.ColumnProto.Column result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v3.ColumnProto.Column buildPartial() {
        com.factset.protobuf.stach.v3.ColumnProto.Column result = new com.factset.protobuf.stach.v3.ColumnProto.Column(this);
        int from_bitField0_ = bitField0_;
        result.contextualType_ = contextualType_;
        result.customMetadata_ = internalGetCustomMetadata();
        result.customMetadata_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.factset.protobuf.stach.v3.ColumnProto.Column) {
          return mergeFrom((com.factset.protobuf.stach.v3.ColumnProto.Column)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.factset.protobuf.stach.v3.ColumnProto.Column other) {
        if (other == com.factset.protobuf.stach.v3.ColumnProto.Column.getDefaultInstance()) return this;
        if (!other.getContextualType().isEmpty()) {
          contextualType_ = other.contextualType_;
          onChanged();
        }
        internalGetMutableCustomMetadata().mergeFrom(
            other.internalGetCustomMetadata());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.factset.protobuf.stach.v3.ColumnProto.Column parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.factset.protobuf.stach.v3.ColumnProto.Column) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object contextualType_ = "";
      /**
       * <pre>
       *The type that defines a higher level contextual type.
       *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
       *Required.
       * </pre>
       *
       * <code>string contextual_type = 1;</code>
       * @return The contextualType.
       */
      public java.lang.String getContextualType() {
        java.lang.Object ref = contextualType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contextualType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *The type that defines a higher level contextual type.
       *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
       *Required.
       * </pre>
       *
       * <code>string contextual_type = 1;</code>
       * @return The bytes for contextualType.
       */
      public com.google.protobuf.ByteString
          getContextualTypeBytes() {
        java.lang.Object ref = contextualType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contextualType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *The type that defines a higher level contextual type.
       *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
       *Required.
       * </pre>
       *
       * <code>string contextual_type = 1;</code>
       * @param value The contextualType to set.
       * @return This builder for chaining.
       */
      public Builder setContextualType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contextualType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The type that defines a higher level contextual type.
       *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
       *Required.
       * </pre>
       *
       * <code>string contextual_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContextualType() {
        
        contextualType_ = getDefaultInstance().getContextualType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *The type that defines a higher level contextual type.
       *E.g. 'email', or 'id32'. Maps to a [logical type](https://arrow.apache.org/docs/format/Columnar.html#logical-types) which needs to be specified as the [Arrow Field `type` property](https://arrow.apache.org/docs/format/Columnar.html#schema-message).
       *Required.
       * </pre>
       *
       * <code>string contextual_type = 1;</code>
       * @param value The bytes for contextualType to set.
       * @return This builder for chaining.
       */
      public Builder setContextualTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contextualType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> customMetadata_;
      private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
      internalGetCustomMetadata() {
        if (customMetadata_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CustomMetadataDefaultEntryHolder.defaultEntry);
        }
        return customMetadata_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
      internalGetMutableCustomMetadata() {
        onChanged();;
        if (customMetadata_ == null) {
          customMetadata_ = com.google.protobuf.MapField.newMapField(
              CustomMetadataDefaultEntryHolder.defaultEntry);
        }
        if (!customMetadata_.isMutable()) {
          customMetadata_ = customMetadata_.copy();
        }
        return customMetadata_;
      }

      public int getCustomMetadataCount() {
        return internalGetCustomMetadata().getMap().size();
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */

      @java.lang.Override
      public boolean containsCustomMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetCustomMetadata().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCustomMetadataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> getCustomMetadata() {
        return getCustomMetadataMap();
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> getCustomMetadataMap() {
        return internalGetCustomMetadata().getMap();
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */
      @java.lang.Override

      public com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrDefault(
          java.lang.String key,
          com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> map =
            internalGetCustomMetadata().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */
      @java.lang.Override

      public com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem getCustomMetadataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> map =
            internalGetCustomMetadata().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCustomMetadata() {
        internalGetMutableCustomMetadata().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */

      public Builder removeCustomMetadata(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableCustomMetadata().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem>
      getMutableCustomMetadata() {
        return internalGetMutableCustomMetadata().getMutableMap();
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */
      public Builder putCustomMetadata(
          java.lang.String key,
          com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableCustomMetadata().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *The custom metadata.
       *Optional.
       * </pre>
       *
       * <code>map&lt;string, .factset.protobuf.stach.v3.MetadataItem&gt; custom_metadata = 100;</code>
       */

      public Builder putAllCustomMetadata(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.v3.MetadataItemProto.MetadataItem> values) {
        internalGetMutableCustomMetadata().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:factset.protobuf.stach.v3.Column)
    }

    // @@protoc_insertion_point(class_scope:factset.protobuf.stach.v3.Column)
    private static final com.factset.protobuf.stach.v3.ColumnProto.Column DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.factset.protobuf.stach.v3.ColumnProto.Column();
    }

    public static com.factset.protobuf.stach.v3.ColumnProto.Column getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Column>
        PARSER = new com.google.protobuf.AbstractParser<Column>() {
      @java.lang.Override
      public Column parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Column(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Column> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Column> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.factset.protobuf.stach.v3.ColumnProto.Column getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_v3_Column_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_v3_Column_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"fds/protobuf/stach/v3/Column.proto\022\031fa" +
      "ctset.protobuf.stach.v3\032(fds/protobuf/st" +
      "ach/v3/MetadataItem.proto\"\321\001\n\006Column\022\027\n\017" +
      "contextual_type\030\001 \001(\t\022N\n\017custom_metadata" +
      "\030d \003(\01325.factset.protobuf.stach.v3.Colum" +
      "n.CustomMetadataEntry\032^\n\023CustomMetadataE" +
      "ntry\022\013\n\003key\030\001 \001(\t\0226\n\005value\030\002 \001(\0132\'.facts" +
      "et.protobuf.stach.v3.MetadataItem:\0028\001B\206\001" +
      "\n\035com.factset.protobuf.stach.v3B\013ColumnP" +
      "rotoZ<github.com/factset/stachschema-sdk" +
      "s/go/fds/protobuf/stach/v3\252\002\031FactSet.Pro" +
      "tobuf.Stach.V3b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.factset.protobuf.stach.v3.MetadataItemProto.getDescriptor(),
        });
    internal_static_factset_protobuf_stach_v3_Column_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factset_protobuf_stach_v3_Column_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_v3_Column_descriptor,
        new java.lang.String[] { "ContextualType", "CustomMetadata", });
    internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_descriptor =
      internal_static_factset_protobuf_stach_v3_Column_descriptor.getNestedTypes().get(0);
    internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_v3_Column_CustomMetadataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.factset.protobuf.stach.v3.MetadataItemProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
