context("Check for classes")	

test_that("Existence check for all classes corresponding to each protobuf model", {	
  expect_true(isClass(factset.protobuf.stach.v2.Package))	
  expect_true(isClass(factset.protobuf.stach.v2.RowOrganizedPackage))	
  expect_true(isClass(factset.protobuf.stach.v2.table.CellDefinition))	
  expect_true(isClass(factset.protobuf.stach.v2.table.ColumnData))	
  expect_true(isClass(factset.protobuf.stach.v2.table.ColumnDefinition))	
  expect_true(isClass(factset.protobuf.stach.v2.table.DataFormat))	
  expect_true(isClass(factset.protobuf.stach.v2.table.HorizontalAlignment))	
  expect_true(isClass(factset.protobuf.stach.v2.table.ListOfMetadata))	
  expect_true(isClass(factset.protobuf.stach.v2.table.MetadataCollection))	
  expect_true(isClass(factset.protobuf.stach.v2.table.MetadataItem))	
  expect_true(isClass(factset.protobuf.stach.v2.table.MetadataLocations))	
  expect_true(isClass(factset.protobuf.stach.v2.table.Reference))	
  expect_true(isClass(factset.protobuf.stach.v2.table.ReferenceType))	
  expect_true(isClass(factset.protobuf.stach.v2.table.RowDefinition))	
  expect_true(isClass(factset.protobuf.stach.v2.table.Table))	
  expect_true(isClass(factset.protobuf.stach.v2.table.TableData))	
  expect_true(isClass(factset.protobuf.stach.v2.table.TableDefinition))	
  expect_true(isClass(factset.protobuf.stach.v2.table.VerticalAlignment))	
}) 