// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/chart/Chart.proto

// Protobuf Java Version: 3.25.5
package com.factset.protobuf.stach.chart;

public final class ChartProto {
  private ChartProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChartOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factset.protobuf.stach.chart.Chart)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return Whether the template field is set.
     */
    boolean hasTemplate();
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return The template.
     */
    com.google.protobuf.Struct getTemplate();
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     */
    com.google.protobuf.StructOrBuilder getTemplateOrBuilder();

    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    boolean containsAttributes(
        java.lang.String key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    getAttributes();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    getAttributesMap();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue);
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    int getPlotsCount();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    boolean containsPlots(
        java.lang.String key);
    /**
     * Use {@link #getPlotsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
    getPlots();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
    getPlotsMap();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot defaultValue);
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    int getSeriesCount();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    boolean containsSeries(
        java.lang.String key);
    /**
     * Use {@link #getSeriesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
    getSeries();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
    getSeriesMap();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series defaultValue);
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    int getDataCount();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    boolean containsData(
        java.lang.String key);
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
    getData();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
    getDataMap();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data defaultValue);
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    com.factset.protobuf.stach.chart.DataProto.Data getDataOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code factset.protobuf.stach.chart.Chart}
   */
  public static final class Chart extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:factset.protobuf.stach.chart.Chart)
      ChartOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Chart.newBuilder() to construct.
    private Chart(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Chart() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Chart();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetAttributes();
        case 3:
          return internalGetPlots();
        case 4:
          return internalGetSeries();
        case 5:
          return internalGetData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.factset.protobuf.stach.chart.ChartProto.Chart.class, com.factset.protobuf.stach.chart.ChartProto.Chart.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPLATE_FIELD_NUMBER = 1;
    private com.google.protobuf.Struct template_;
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return Whether the template field is set.
     */
    @java.lang.Override
    public boolean hasTemplate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return The template.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getTemplate() {
      return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
    }
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getTemplateOrBuilder() {
      return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 2;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>newDefaultInstance(
                  com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> attributes_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PLOTS_FIELD_NUMBER = 3;
    private static final class PlotsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>newDefaultInstance(
                  com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.chart.PlotProto.Plot.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> plots_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
    internalGetPlots() {
      if (plots_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PlotsDefaultEntryHolder.defaultEntry);
      }
      return plots_;
    }
    public int getPlotsCount() {
      return internalGetPlots().getMap().size();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    @java.lang.Override
    public boolean containsPlots(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetPlots().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPlotsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> getPlots() {
      return getPlotsMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> getPlotsMap() {
      return internalGetPlots().getMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    @java.lang.Override
    public /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> map =
          internalGetPlots().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> map =
          internalGetPlots().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int SERIES_FIELD_NUMBER = 4;
    private static final class SeriesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>newDefaultInstance(
                  com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.chart.SeriesProto.Series.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> series_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
    internalGetSeries() {
      if (series_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SeriesDefaultEntryHolder.defaultEntry);
      }
      return series_;
    }
    public int getSeriesCount() {
      return internalGetSeries().getMap().size();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    @java.lang.Override
    public boolean containsSeries(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSeries().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSeriesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> getSeries() {
      return getSeriesMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> getSeriesMap() {
      return internalGetSeries().getMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> map =
          internalGetSeries().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> map =
          internalGetSeries().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private static final class DataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>newDefaultInstance(
                  com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_DataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.chart.DataProto.Data.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> data_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
    internalGetData() {
      if (data_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            DataDefaultEntryHolder.defaultEntry);
      }
      return data_;
    }
    public int getDataCount() {
      return internalGetData().getMap().size();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    @java.lang.Override
    public boolean containsData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> getData() {
      return getDataMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> getDataMap() {
      return internalGetData().getMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    @java.lang.Override
    public /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data getDataOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> map =
          internalGetData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.chart.DataProto.Data getDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> map =
          internalGetData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTemplate());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          2);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPlots(),
          PlotsDefaultEntryHolder.defaultEntry,
          3);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetSeries(),
          SeriesDefaultEntryHolder.defaultEntry,
          4);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetData(),
          DataDefaultEntryHolder.defaultEntry,
          5);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTemplate());
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, attributes__);
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> entry
           : internalGetPlots().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
        plots__ = PlotsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, plots__);
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> entry
           : internalGetSeries().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
        series__ = SeriesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, series__);
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> entry
           : internalGetData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
        data__ = DataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, data__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.factset.protobuf.stach.chart.ChartProto.Chart)) {
        return super.equals(obj);
      }
      com.factset.protobuf.stach.chart.ChartProto.Chart other = (com.factset.protobuf.stach.chart.ChartProto.Chart) obj;

      if (hasTemplate() != other.hasTemplate()) return false;
      if (hasTemplate()) {
        if (!getTemplate()
            .equals(other.getTemplate())) return false;
      }
      if (!internalGetAttributes().equals(
          other.internalGetAttributes())) return false;
      if (!internalGetPlots().equals(
          other.internalGetPlots())) return false;
      if (!internalGetSeries().equals(
          other.internalGetSeries())) return false;
      if (!internalGetData().equals(
          other.internalGetData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTemplate()) {
        hash = (37 * hash) + TEMPLATE_FIELD_NUMBER;
        hash = (53 * hash) + getTemplate().hashCode();
      }
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      if (!internalGetPlots().getMap().isEmpty()) {
        hash = (37 * hash) + PLOTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPlots().hashCode();
      }
      if (!internalGetSeries().getMap().isEmpty()) {
        hash = (37 * hash) + SERIES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSeries().hashCode();
      }
      if (!internalGetData().getMap().isEmpty()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetData().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.chart.ChartProto.Chart parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.factset.protobuf.stach.chart.ChartProto.Chart prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code factset.protobuf.stach.chart.Chart}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factset.protobuf.stach.chart.Chart)
        com.factset.protobuf.stach.chart.ChartProto.ChartOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetAttributes();
          case 3:
            return internalGetPlots();
          case 4:
            return internalGetSeries();
          case 5:
            return internalGetData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableAttributes();
          case 3:
            return internalGetMutablePlots();
          case 4:
            return internalGetMutableSeries();
          case 5:
            return internalGetMutableData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.factset.protobuf.stach.chart.ChartProto.Chart.class, com.factset.protobuf.stach.chart.ChartProto.Chart.Builder.class);
      }

      // Construct using com.factset.protobuf.stach.chart.ChartProto.Chart.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTemplateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        template_ = null;
        if (templateBuilder_ != null) {
          templateBuilder_.dispose();
          templateBuilder_ = null;
        }
        internalGetMutableAttributes().clear();
        internalGetMutablePlots().clear();
        internalGetMutableSeries().clear();
        internalGetMutableData().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.factset.protobuf.stach.chart.ChartProto.internal_static_factset_protobuf_stach_chart_Chart_descriptor;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.ChartProto.Chart getDefaultInstanceForType() {
        return com.factset.protobuf.stach.chart.ChartProto.Chart.getDefaultInstance();
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.ChartProto.Chart build() {
        com.factset.protobuf.stach.chart.ChartProto.Chart result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.ChartProto.Chart buildPartial() {
        com.factset.protobuf.stach.chart.ChartProto.Chart result = new com.factset.protobuf.stach.chart.ChartProto.Chart(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.factset.protobuf.stach.chart.ChartProto.Chart result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.template_ = templateBuilder_ == null
              ? template_
              : templateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.attributes_ = internalGetAttributes().build(AttributesDefaultEntryHolder.defaultEntry);
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.plots_ = internalGetPlots().build(PlotsDefaultEntryHolder.defaultEntry);
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.series_ = internalGetSeries().build(SeriesDefaultEntryHolder.defaultEntry);
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.data_ = internalGetData().build(DataDefaultEntryHolder.defaultEntry);
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.factset.protobuf.stach.chart.ChartProto.Chart) {
          return mergeFrom((com.factset.protobuf.stach.chart.ChartProto.Chart)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.factset.protobuf.stach.chart.ChartProto.Chart other) {
        if (other == com.factset.protobuf.stach.chart.ChartProto.Chart.getDefaultInstance()) return this;
        if (other.hasTemplate()) {
          mergeTemplate(other.getTemplate());
        }
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        bitField0_ |= 0x00000002;
        internalGetMutablePlots().mergeFrom(
            other.internalGetPlots());
        bitField0_ |= 0x00000004;
        internalGetMutableSeries().mergeFrom(
            other.internalGetSeries());
        bitField0_ |= 0x00000008;
        internalGetMutableData().mergeFrom(
            other.internalGetData());
        bitField0_ |= 0x00000010;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTemplateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
                attributes__ = input.readMessage(
                    AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAttributes().ensureBuilderMap().put(
                    attributes__.getKey(), attributes__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
                plots__ = input.readMessage(
                    PlotsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutablePlots().ensureBuilderMap().put(
                    plots__.getKey(), plots__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
                series__ = input.readMessage(
                    SeriesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableSeries().ensureBuilderMap().put(
                    series__.getKey(), series__.getValue());
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
                data__ = input.readMessage(
                    DataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableData().ensureBuilderMap().put(
                    data__.getKey(), data__.getValue());
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Struct template_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> templateBuilder_;
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       * @return Whether the template field is set.
       */
      public boolean hasTemplate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       * @return The template.
       */
      public com.google.protobuf.Struct getTemplate() {
        if (templateBuilder_ == null) {
          return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
        } else {
          return templateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder setTemplate(com.google.protobuf.Struct value) {
        if (templateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          template_ = value;
        } else {
          templateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder setTemplate(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (templateBuilder_ == null) {
          template_ = builderForValue.build();
        } else {
          templateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder mergeTemplate(com.google.protobuf.Struct value) {
        if (templateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            template_ != null &&
            template_ != com.google.protobuf.Struct.getDefaultInstance()) {
            getTemplateBuilder().mergeFrom(value);
          } else {
            template_ = value;
          }
        } else {
          templateBuilder_.mergeFrom(value);
        }
        if (template_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder clearTemplate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        template_ = null;
        if (templateBuilder_ != null) {
          templateBuilder_.dispose();
          templateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public com.google.protobuf.Struct.Builder getTemplateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTemplateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public com.google.protobuf.StructOrBuilder getTemplateOrBuilder() {
        if (templateBuilder_ != null) {
          return templateBuilder_.getMessageOrBuilder();
        } else {
          return template_ == null ?
              com.google.protobuf.Struct.getDefaultInstance() : template_;
        }
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          getTemplateFieldBuilder() {
        if (templateBuilder_ == null) {
          templateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  getTemplate(),
                  getParentForChildren(),
                  isClean());
          template_ = null;
        }
        return templateBuilder_;
      }

      private static final class AttributesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference> {
        @java.lang.Override
        public com.factset.protobuf.stach.table.ReferenceProto.Reference build(com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder val) {
          if (val instanceof com.factset.protobuf.stach.table.ReferenceProto.Reference) { return (com.factset.protobuf.stach.table.ReferenceProto.Reference) val; }
          return ((com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> defaultEntry() {
          return AttributesDefaultEntryHolder.defaultEntry;
        }
      };
      private static final AttributesConverter attributesConverter = new AttributesConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder> attributes_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder>
          internalGetAttributes() {
        if (attributes_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(attributesConverter);
        }
        return attributes_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder>
          internalGetMutableAttributes() {
        if (attributes_ == null) {
          attributes_ = new com.google.protobuf.MapFieldBuilder<>(attributesConverter);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return attributes_;
      }
      public int getAttributesCount() {
        return internalGetAttributes().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public boolean containsAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetAttributes().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributesMap() {
        return internalGetAttributes().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
          java.lang.String key,
          /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> map = internalGetMutableAttributes().ensureBuilderMap();
        return map.containsKey(key) ? attributesConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> map = internalGetMutableAttributes().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return attributesConverter.build(map.get(key));
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableAttributes().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder removeAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableAttributes().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
          getMutableAttributes() {
        bitField0_ |= 0x00000002;
        return internalGetMutableAttributes().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder putAttributes(
          java.lang.String key,
          com.factset.protobuf.stach.table.ReferenceProto.Reference value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAttributes().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder putAllAttributes(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> values) {
        for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableAttributes().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder putAttributesBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> builderMap = internalGetMutableAttributes().ensureBuilderMap();
        com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.factset.protobuf.stach.table.ReferenceProto.Reference.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.factset.protobuf.stach.table.ReferenceProto.Reference) {
          entry = ((com.factset.protobuf.stach.table.ReferenceProto.Reference) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder) entry;
      }

      private static final class PlotsConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder, com.factset.protobuf.stach.chart.PlotProto.Plot> {
        @java.lang.Override
        public com.factset.protobuf.stach.chart.PlotProto.Plot build(com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder val) {
          if (val instanceof com.factset.protobuf.stach.chart.PlotProto.Plot) { return (com.factset.protobuf.stach.chart.PlotProto.Plot) val; }
          return ((com.factset.protobuf.stach.chart.PlotProto.Plot.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> defaultEntry() {
          return PlotsDefaultEntryHolder.defaultEntry;
        }
      };
      private static final PlotsConverter plotsConverter = new PlotsConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder, com.factset.protobuf.stach.chart.PlotProto.Plot, com.factset.protobuf.stach.chart.PlotProto.Plot.Builder> plots_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder, com.factset.protobuf.stach.chart.PlotProto.Plot, com.factset.protobuf.stach.chart.PlotProto.Plot.Builder>
          internalGetPlots() {
        if (plots_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(plotsConverter);
        }
        return plots_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder, com.factset.protobuf.stach.chart.PlotProto.Plot, com.factset.protobuf.stach.chart.PlotProto.Plot.Builder>
          internalGetMutablePlots() {
        if (plots_ == null) {
          plots_ = new com.google.protobuf.MapFieldBuilder<>(plotsConverter);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return plots_;
      }
      public int getPlotsCount() {
        return internalGetPlots().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      @java.lang.Override
      public boolean containsPlots(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetPlots().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getPlotsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> getPlots() {
        return getPlotsMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> getPlotsMap() {
        return internalGetPlots().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      @java.lang.Override
      public /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrDefault(
          java.lang.String key,
          /* nullable */
com.factset.protobuf.stach.chart.PlotProto.Plot defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder> map = internalGetMutablePlots().ensureBuilderMap();
        return map.containsKey(key) ? plotsConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      @java.lang.Override
      public com.factset.protobuf.stach.chart.PlotProto.Plot getPlotsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder> map = internalGetMutablePlots().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return plotsConverter.build(map.get(key));
      }
      public Builder clearPlots() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutablePlots().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      public Builder removePlots(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutablePlots().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot>
          getMutablePlots() {
        bitField0_ |= 0x00000004;
        return internalGetMutablePlots().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      public Builder putPlots(
          java.lang.String key,
          com.factset.protobuf.stach.chart.PlotProto.Plot value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutablePlots().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      public Builder putAllPlots(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> values) {
        for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.Plot> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutablePlots().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Plot&gt; plots = 3;</code>
       */
      public com.factset.protobuf.stach.chart.PlotProto.Plot.Builder putPlotsBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder> builderMap = internalGetMutablePlots().ensureBuilderMap();
        com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.factset.protobuf.stach.chart.PlotProto.Plot.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.factset.protobuf.stach.chart.PlotProto.Plot) {
          entry = ((com.factset.protobuf.stach.chart.PlotProto.Plot) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.factset.protobuf.stach.chart.PlotProto.Plot.Builder) entry;
      }

      private static final class SeriesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder, com.factset.protobuf.stach.chart.SeriesProto.Series> {
        @java.lang.Override
        public com.factset.protobuf.stach.chart.SeriesProto.Series build(com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder val) {
          if (val instanceof com.factset.protobuf.stach.chart.SeriesProto.Series) { return (com.factset.protobuf.stach.chart.SeriesProto.Series) val; }
          return ((com.factset.protobuf.stach.chart.SeriesProto.Series.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> defaultEntry() {
          return SeriesDefaultEntryHolder.defaultEntry;
        }
      };
      private static final SeriesConverter seriesConverter = new SeriesConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder, com.factset.protobuf.stach.chart.SeriesProto.Series, com.factset.protobuf.stach.chart.SeriesProto.Series.Builder> series_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder, com.factset.protobuf.stach.chart.SeriesProto.Series, com.factset.protobuf.stach.chart.SeriesProto.Series.Builder>
          internalGetSeries() {
        if (series_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(seriesConverter);
        }
        return series_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder, com.factset.protobuf.stach.chart.SeriesProto.Series, com.factset.protobuf.stach.chart.SeriesProto.Series.Builder>
          internalGetMutableSeries() {
        if (series_ == null) {
          series_ = new com.google.protobuf.MapFieldBuilder<>(seriesConverter);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return series_;
      }
      public int getSeriesCount() {
        return internalGetSeries().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      @java.lang.Override
      public boolean containsSeries(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetSeries().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getSeriesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> getSeries() {
        return getSeriesMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> getSeriesMap() {
        return internalGetSeries().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      @java.lang.Override
      public /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrDefault(
          java.lang.String key,
          /* nullable */
com.factset.protobuf.stach.chart.SeriesProto.Series defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder> map = internalGetMutableSeries().ensureBuilderMap();
        return map.containsKey(key) ? seriesConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      @java.lang.Override
      public com.factset.protobuf.stach.chart.SeriesProto.Series getSeriesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder> map = internalGetMutableSeries().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return seriesConverter.build(map.get(key));
      }
      public Builder clearSeries() {
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableSeries().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      public Builder removeSeries(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableSeries().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series>
          getMutableSeries() {
        bitField0_ |= 0x00000008;
        return internalGetMutableSeries().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      public Builder putSeries(
          java.lang.String key,
          com.factset.protobuf.stach.chart.SeriesProto.Series value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableSeries().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      public Builder putAllSeries(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> values) {
        for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.Series> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableSeries().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Series&gt; series = 4;</code>
       */
      public com.factset.protobuf.stach.chart.SeriesProto.Series.Builder putSeriesBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder> builderMap = internalGetMutableSeries().ensureBuilderMap();
        com.factset.protobuf.stach.chart.SeriesProto.SeriesOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.factset.protobuf.stach.chart.SeriesProto.Series.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.factset.protobuf.stach.chart.SeriesProto.Series) {
          entry = ((com.factset.protobuf.stach.chart.SeriesProto.Series) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.factset.protobuf.stach.chart.SeriesProto.Series.Builder) entry;
      }

      private static final class DataConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder, com.factset.protobuf.stach.chart.DataProto.Data> {
        @java.lang.Override
        public com.factset.protobuf.stach.chart.DataProto.Data build(com.factset.protobuf.stach.chart.DataProto.DataOrBuilder val) {
          if (val instanceof com.factset.protobuf.stach.chart.DataProto.Data) { return (com.factset.protobuf.stach.chart.DataProto.Data) val; }
          return ((com.factset.protobuf.stach.chart.DataProto.Data.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> defaultEntry() {
          return DataDefaultEntryHolder.defaultEntry;
        }
      };
      private static final DataConverter dataConverter = new DataConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder, com.factset.protobuf.stach.chart.DataProto.Data, com.factset.protobuf.stach.chart.DataProto.Data.Builder> data_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder, com.factset.protobuf.stach.chart.DataProto.Data, com.factset.protobuf.stach.chart.DataProto.Data.Builder>
          internalGetData() {
        if (data_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(dataConverter);
        }
        return data_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder, com.factset.protobuf.stach.chart.DataProto.Data, com.factset.protobuf.stach.chart.DataProto.Data.Builder>
          internalGetMutableData() {
        if (data_ == null) {
          data_ = new com.google.protobuf.MapFieldBuilder<>(dataConverter);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return data_;
      }
      public int getDataCount() {
        return internalGetData().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      @java.lang.Override
      public boolean containsData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetData().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> getData() {
        return getDataMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> getDataMap() {
        return internalGetData().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      @java.lang.Override
      public /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data getDataOrDefault(
          java.lang.String key,
          /* nullable */
com.factset.protobuf.stach.chart.DataProto.Data defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder> map = internalGetMutableData().ensureBuilderMap();
        return map.containsKey(key) ? dataConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      @java.lang.Override
      public com.factset.protobuf.stach.chart.DataProto.Data getDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder> map = internalGetMutableData().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return dataConverter.build(map.get(key));
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000010);
        internalGetMutableData().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      public Builder removeData(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableData().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data>
          getMutableData() {
        bitField0_ |= 0x00000010;
        return internalGetMutableData().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      public Builder putData(
          java.lang.String key,
          com.factset.protobuf.stach.chart.DataProto.Data value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableData().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      public Builder putAllData(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> values) {
        for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.chart.DataProto.Data> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableData().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.chart.Data&gt; data = 5;</code>
       */
      public com.factset.protobuf.stach.chart.DataProto.Data.Builder putDataBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.factset.protobuf.stach.chart.DataProto.DataOrBuilder> builderMap = internalGetMutableData().ensureBuilderMap();
        com.factset.protobuf.stach.chart.DataProto.DataOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.factset.protobuf.stach.chart.DataProto.Data.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.factset.protobuf.stach.chart.DataProto.Data) {
          entry = ((com.factset.protobuf.stach.chart.DataProto.Data) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.factset.protobuf.stach.chart.DataProto.Data.Builder) entry;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:factset.protobuf.stach.chart.Chart)
    }

    // @@protoc_insertion_point(class_scope:factset.protobuf.stach.chart.Chart)
    private static final com.factset.protobuf.stach.chart.ChartProto.Chart DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.factset.protobuf.stach.chart.ChartProto.Chart();
    }

    public static com.factset.protobuf.stach.chart.ChartProto.Chart getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Chart>
        PARSER = new com.google.protobuf.AbstractParser<Chart>() {
      @java.lang.Override
      public Chart parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Chart> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Chart> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.factset.protobuf.stach.chart.ChartProto.Chart getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Chart_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Chart_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Chart_DataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Chart_DataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$fds/protobuf/stach/chart/Chart.proto\022\034" +
      "factset.protobuf.stach.chart\032\034google/pro" +
      "tobuf/struct.proto\032#fds/protobuf/stach/c" +
      "hart/Plot.proto\032#fds/protobuf/stach/char" +
      "t/Data.proto\032%fds/protobuf/stach/chart/S" +
      "eries.proto\032(fds/protobuf/stach/table/Re" +
      "ference.proto\"\214\005\n\005Chart\022)\n\010template\030\001 \001(" +
      "\0132\027.google.protobuf.Struct\022G\n\nattributes" +
      "\030\002 \003(\01323.factset.protobuf.stach.chart.Ch" +
      "art.AttributesEntry\022=\n\005plots\030\003 \003(\0132..fac" +
      "tset.protobuf.stach.chart.Chart.PlotsEnt" +
      "ry\022?\n\006series\030\004 \003(\0132/.factset.protobuf.st" +
      "ach.chart.Chart.SeriesEntry\022;\n\004data\030\005 \003(" +
      "\0132-.factset.protobuf.stach.chart.Chart.D" +
      "ataEntry\032Z\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t" +
      "\0226\n\005value\030\002 \001(\0132\'.factset.protobuf.stach" +
      ".table.Reference:\0028\001\032P\n\nPlotsEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".factset.protobu" +
      "f.stach.chart.Plot:\0028\001\032S\n\013SeriesEntry\022\013\n" +
      "\003key\030\001 \001(\t\0223\n\005value\030\002 \001(\0132$.factset.prot" +
      "obuf.stach.chart.Series:\0028\001\032O\n\tDataEntry" +
      "\022\013\n\003key\030\001 \001(\t\0221\n\005value\030\002 \001(\0132\".factset.p" +
      "rotobuf.stach.chart.Data:\0028\001BM\n com.fact" +
      "set.protobuf.stach.chartB\nChartProto\252\002\034F" +
      "actSet.Protobuf.Stach.Chartb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.factset.protobuf.stach.chart.PlotProto.getDescriptor(),
          com.factset.protobuf.stach.chart.DataProto.getDescriptor(),
          com.factset.protobuf.stach.chart.SeriesProto.getDescriptor(),
          com.factset.protobuf.stach.table.ReferenceProto.getDescriptor(),
        });
    internal_static_factset_protobuf_stach_chart_Chart_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factset_protobuf_stach_chart_Chart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Chart_descriptor,
        new java.lang.String[] { "Template", "Attributes", "Plots", "Series", "Data", });
    internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_descriptor =
      internal_static_factset_protobuf_stach_chart_Chart_descriptor.getNestedTypes().get(0);
    internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Chart_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_descriptor =
      internal_static_factset_protobuf_stach_chart_Chart_descriptor.getNestedTypes().get(1);
    internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Chart_PlotsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_descriptor =
      internal_static_factset_protobuf_stach_chart_Chart_descriptor.getNestedTypes().get(2);
    internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Chart_SeriesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_factset_protobuf_stach_chart_Chart_DataEntry_descriptor =
      internal_static_factset_protobuf_stach_chart_Chart_descriptor.getNestedTypes().get(3);
    internal_static_factset_protobuf_stach_chart_Chart_DataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Chart_DataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
    com.factset.protobuf.stach.chart.PlotProto.getDescriptor();
    com.factset.protobuf.stach.chart.DataProto.getDescriptor();
    com.factset.protobuf.stach.chart.SeriesProto.getDescriptor();
    com.factset.protobuf.stach.table.ReferenceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
