// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/chart/Plot.proto

// Protobuf Java Version: 3.25.5
package com.factset.protobuf.stach.chart;

public final class PlotProto {
  private PlotProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlotOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factset.protobuf.stach.chart.Plot)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return Whether the template field is set.
     */
    boolean hasTemplate();
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return The template.
     */
    com.google.protobuf.Struct getTemplate();
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     */
    com.google.protobuf.StructOrBuilder getTemplateOrBuilder();

    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    int getAttributesCount();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    boolean containsAttributes(
        java.lang.String key);
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    getAttributes();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    getAttributesMap();
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue);
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
        java.lang.String key);

    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     * @return Whether the label field is set.
     */
    boolean hasLabel();
    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     * @return The label.
     */
    com.factset.protobuf.stach.table.ReferenceProto.Reference getLabel();
    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     */
    com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder getLabelOrBuilder();

    /**
     * <code>repeated string series = 4;</code>
     * @return A list containing the series.
     */
    java.util.List<java.lang.String>
        getSeriesList();
    /**
     * <code>repeated string series = 4;</code>
     * @return The count of series.
     */
    int getSeriesCount();
    /**
     * <code>repeated string series = 4;</code>
     * @param index The index of the element to return.
     * @return The series at the given index.
     */
    java.lang.String getSeries(int index);
    /**
     * <code>repeated string series = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the series at the given index.
     */
    com.google.protobuf.ByteString
        getSeriesBytes(int index);
  }
  /**
   * Protobuf type {@code factset.protobuf.stach.chart.Plot}
   */
  public static final class Plot extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:factset.protobuf.stach.chart.Plot)
      PlotOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Plot.newBuilder() to construct.
    private Plot(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Plot() {
      series_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Plot();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetAttributes();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.factset.protobuf.stach.chart.PlotProto.Plot.class, com.factset.protobuf.stach.chart.PlotProto.Plot.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPLATE_FIELD_NUMBER = 1;
    private com.google.protobuf.Struct template_;
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return Whether the template field is set.
     */
    @java.lang.Override
    public boolean hasTemplate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     * @return The template.
     */
    @java.lang.Override
    public com.google.protobuf.Struct getTemplate() {
      return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
    }
    /**
     * <code>.google.protobuf.Struct template = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.StructOrBuilder getTemplateOrBuilder() {
      return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
    }

    public static final int ATTRIBUTES_FIELD_NUMBER = 2;
    private static final class AttributesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>newDefaultInstance(
                  com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> attributes_;
    private com.google.protobuf.MapField<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
    internalGetAttributes() {
      if (attributes_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttributesDefaultEntryHolder.defaultEntry);
      }
      return attributes_;
    }
    public int getAttributesCount() {
      return internalGetAttributes().getMap().size();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public boolean containsAttributes(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAttributes().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttributesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributes() {
      return getAttributesMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributesMap() {
      return internalGetAttributes().getMap();
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
        java.lang.String key,
        /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> map =
          internalGetAttributes().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> map =
          internalGetAttributes().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int LABEL_FIELD_NUMBER = 3;
    private com.factset.protobuf.stach.table.ReferenceProto.Reference label_;
    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     * @return Whether the label field is set.
     */
    @java.lang.Override
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     * @return The label.
     */
    @java.lang.Override
    public com.factset.protobuf.stach.table.ReferenceProto.Reference getLabel() {
      return label_ == null ? com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance() : label_;
    }
    /**
     * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder getLabelOrBuilder() {
      return label_ == null ? com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance() : label_;
    }

    public static final int SERIES_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList series_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string series = 4;</code>
     * @return A list containing the series.
     */
    public com.google.protobuf.ProtocolStringList
        getSeriesList() {
      return series_;
    }
    /**
     * <code>repeated string series = 4;</code>
     * @return The count of series.
     */
    public int getSeriesCount() {
      return series_.size();
    }
    /**
     * <code>repeated string series = 4;</code>
     * @param index The index of the element to return.
     * @return The series at the given index.
     */
    public java.lang.String getSeries(int index) {
      return series_.get(index);
    }
    /**
     * <code>repeated string series = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the series at the given index.
     */
    public com.google.protobuf.ByteString
        getSeriesBytes(int index) {
      return series_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getTemplate());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttributes(),
          AttributesDefaultEntryHolder.defaultEntry,
          2);
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getLabel());
      }
      for (int i = 0; i < series_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, series_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTemplate());
      }
      for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> entry
           : internalGetAttributes().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
        attributes__ = AttributesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, attributes__);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLabel());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < series_.size(); i++) {
          dataSize += computeStringSizeNoTag(series_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSeriesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.factset.protobuf.stach.chart.PlotProto.Plot)) {
        return super.equals(obj);
      }
      com.factset.protobuf.stach.chart.PlotProto.Plot other = (com.factset.protobuf.stach.chart.PlotProto.Plot) obj;

      if (hasTemplate() != other.hasTemplate()) return false;
      if (hasTemplate()) {
        if (!getTemplate()
            .equals(other.getTemplate())) return false;
      }
      if (!internalGetAttributes().equals(
          other.internalGetAttributes())) return false;
      if (hasLabel() != other.hasLabel()) return false;
      if (hasLabel()) {
        if (!getLabel()
            .equals(other.getLabel())) return false;
      }
      if (!getSeriesList()
          .equals(other.getSeriesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTemplate()) {
        hash = (37 * hash) + TEMPLATE_FIELD_NUMBER;
        hash = (53 * hash) + getTemplate().hashCode();
      }
      if (!internalGetAttributes().getMap().isEmpty()) {
        hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttributes().hashCode();
      }
      if (hasLabel()) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabel().hashCode();
      }
      if (getSeriesCount() > 0) {
        hash = (37 * hash) + SERIES_FIELD_NUMBER;
        hash = (53 * hash) + getSeriesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.chart.PlotProto.Plot parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.factset.protobuf.stach.chart.PlotProto.Plot prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code factset.protobuf.stach.chart.Plot}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factset.protobuf.stach.chart.Plot)
        com.factset.protobuf.stach.chart.PlotProto.PlotOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableAttributes();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.factset.protobuf.stach.chart.PlotProto.Plot.class, com.factset.protobuf.stach.chart.PlotProto.Plot.Builder.class);
      }

      // Construct using com.factset.protobuf.stach.chart.PlotProto.Plot.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTemplateFieldBuilder();
          getLabelFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        template_ = null;
        if (templateBuilder_ != null) {
          templateBuilder_.dispose();
          templateBuilder_ = null;
        }
        internalGetMutableAttributes().clear();
        label_ = null;
        if (labelBuilder_ != null) {
          labelBuilder_.dispose();
          labelBuilder_ = null;
        }
        series_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.factset.protobuf.stach.chart.PlotProto.internal_static_factset_protobuf_stach_chart_Plot_descriptor;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.PlotProto.Plot getDefaultInstanceForType() {
        return com.factset.protobuf.stach.chart.PlotProto.Plot.getDefaultInstance();
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.PlotProto.Plot build() {
        com.factset.protobuf.stach.chart.PlotProto.Plot result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.chart.PlotProto.Plot buildPartial() {
        com.factset.protobuf.stach.chart.PlotProto.Plot result = new com.factset.protobuf.stach.chart.PlotProto.Plot(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.factset.protobuf.stach.chart.PlotProto.Plot result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.template_ = templateBuilder_ == null
              ? template_
              : templateBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.attributes_ = internalGetAttributes().build(AttributesDefaultEntryHolder.defaultEntry);
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.label_ = labelBuilder_ == null
              ? label_
              : labelBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          series_.makeImmutable();
          result.series_ = series_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.factset.protobuf.stach.chart.PlotProto.Plot) {
          return mergeFrom((com.factset.protobuf.stach.chart.PlotProto.Plot)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.factset.protobuf.stach.chart.PlotProto.Plot other) {
        if (other == com.factset.protobuf.stach.chart.PlotProto.Plot.getDefaultInstance()) return this;
        if (other.hasTemplate()) {
          mergeTemplate(other.getTemplate());
        }
        internalGetMutableAttributes().mergeFrom(
            other.internalGetAttributes());
        bitField0_ |= 0x00000002;
        if (other.hasLabel()) {
          mergeLabel(other.getLabel());
        }
        if (!other.series_.isEmpty()) {
          if (series_.isEmpty()) {
            series_ = other.series_;
            bitField0_ |= 0x00000008;
          } else {
            ensureSeriesIsMutable();
            series_.addAll(other.series_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getTemplateFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
                attributes__ = input.readMessage(
                    AttributesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAttributes().ensureBuilderMap().put(
                    attributes__.getKey(), attributes__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getLabelFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureSeriesIsMutable();
                series_.add(s);
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Struct template_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> templateBuilder_;
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       * @return Whether the template field is set.
       */
      public boolean hasTemplate() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       * @return The template.
       */
      public com.google.protobuf.Struct getTemplate() {
        if (templateBuilder_ == null) {
          return template_ == null ? com.google.protobuf.Struct.getDefaultInstance() : template_;
        } else {
          return templateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder setTemplate(com.google.protobuf.Struct value) {
        if (templateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          template_ = value;
        } else {
          templateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder setTemplate(
          com.google.protobuf.Struct.Builder builderForValue) {
        if (templateBuilder_ == null) {
          template_ = builderForValue.build();
        } else {
          templateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder mergeTemplate(com.google.protobuf.Struct value) {
        if (templateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            template_ != null &&
            template_ != com.google.protobuf.Struct.getDefaultInstance()) {
            getTemplateBuilder().mergeFrom(value);
          } else {
            template_ = value;
          }
        } else {
          templateBuilder_.mergeFrom(value);
        }
        if (template_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public Builder clearTemplate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        template_ = null;
        if (templateBuilder_ != null) {
          templateBuilder_.dispose();
          templateBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public com.google.protobuf.Struct.Builder getTemplateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTemplateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      public com.google.protobuf.StructOrBuilder getTemplateOrBuilder() {
        if (templateBuilder_ != null) {
          return templateBuilder_.getMessageOrBuilder();
        } else {
          return template_ == null ?
              com.google.protobuf.Struct.getDefaultInstance() : template_;
        }
      }
      /**
       * <code>.google.protobuf.Struct template = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
          getTemplateFieldBuilder() {
        if (templateBuilder_ == null) {
          templateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                  getTemplate(),
                  getParentForChildren(),
                  isClean());
          template_ = null;
        }
        return templateBuilder_;
      }

      private static final class AttributesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference> {
        @java.lang.Override
        public com.factset.protobuf.stach.table.ReferenceProto.Reference build(com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder val) {
          if (val instanceof com.factset.protobuf.stach.table.ReferenceProto.Reference) { return (com.factset.protobuf.stach.table.ReferenceProto.Reference) val; }
          return ((com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder) val).build();
        }

        @java.lang.Override
        public com.google.protobuf.MapEntry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> defaultEntry() {
          return AttributesDefaultEntryHolder.defaultEntry;
        }
      };
      private static final AttributesConverter attributesConverter = new AttributesConverter();

      private com.google.protobuf.MapFieldBuilder<
          java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder> attributes_;
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder>
          internalGetAttributes() {
        if (attributes_ == null) {
          return new com.google.protobuf.MapFieldBuilder<>(attributesConverter);
        }
        return attributes_;
      }
      private com.google.protobuf.MapFieldBuilder<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder, com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder>
          internalGetMutableAttributes() {
        if (attributes_ == null) {
          attributes_ = new com.google.protobuf.MapFieldBuilder<>(attributesConverter);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return attributes_;
      }
      public int getAttributesCount() {
        return internalGetAttributes().ensureBuilderMap().size();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public boolean containsAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetAttributes().ensureBuilderMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributesMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributes() {
        return getAttributesMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> getAttributesMap() {
        return internalGetAttributes().getImmutableMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrDefault(
          java.lang.String key,
          /* nullable */
com.factset.protobuf.stach.table.ReferenceProto.Reference defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> map = internalGetMutableAttributes().ensureBuilderMap();
        return map.containsKey(key) ? attributesConverter.build(map.get(key)) : defaultValue;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      @java.lang.Override
      public com.factset.protobuf.stach.table.ReferenceProto.Reference getAttributesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> map = internalGetMutableAttributes().ensureBuilderMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return attributesConverter.build(map.get(key));
      }
      public Builder clearAttributes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableAttributes().clear();
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder removeAttributes(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableAttributes().ensureBuilderMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference>
          getMutableAttributes() {
        bitField0_ |= 0x00000002;
        return internalGetMutableAttributes().ensureMessageMap();
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder putAttributes(
          java.lang.String key,
          com.factset.protobuf.stach.table.ReferenceProto.Reference value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAttributes().ensureBuilderMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public Builder putAllAttributes(
          java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> values) {
        for (java.util.Map.Entry<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.Reference> e : values.entrySet()) {
          if (e.getKey() == null || e.getValue() == null) {
            throw new NullPointerException();
          }
        }
        internalGetMutableAttributes().ensureBuilderMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .factset.protobuf.stach.table.Reference&gt; attributes = 2;</code>
       */
      public com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder putAttributesBuilderIfAbsent(
          java.lang.String key) {
        java.util.Map<java.lang.String, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> builderMap = internalGetMutableAttributes().ensureBuilderMap();
        com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder entry = builderMap.get(key);
        if (entry == null) {
          entry = com.factset.protobuf.stach.table.ReferenceProto.Reference.newBuilder();
          builderMap.put(key, entry);
        }
        if (entry instanceof com.factset.protobuf.stach.table.ReferenceProto.Reference) {
          entry = ((com.factset.protobuf.stach.table.ReferenceProto.Reference) entry).toBuilder();
          builderMap.put(key, entry);
        }
        return (com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder) entry;
      }

      private com.factset.protobuf.stach.table.ReferenceProto.Reference label_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> labelBuilder_;
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       * @return Whether the label field is set.
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       * @return The label.
       */
      public com.factset.protobuf.stach.table.ReferenceProto.Reference getLabel() {
        if (labelBuilder_ == null) {
          return label_ == null ? com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance() : label_;
        } else {
          return labelBuilder_.getMessage();
        }
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public Builder setLabel(com.factset.protobuf.stach.table.ReferenceProto.Reference value) {
        if (labelBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          label_ = value;
        } else {
          labelBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public Builder setLabel(
          com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder builderForValue) {
        if (labelBuilder_ == null) {
          label_ = builderForValue.build();
        } else {
          labelBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public Builder mergeLabel(com.factset.protobuf.stach.table.ReferenceProto.Reference value) {
        if (labelBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            label_ != null &&
            label_ != com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance()) {
            getLabelBuilder().mergeFrom(value);
          } else {
            label_ = value;
          }
        } else {
          labelBuilder_.mergeFrom(value);
        }
        if (label_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        label_ = null;
        if (labelBuilder_ != null) {
          labelBuilder_.dispose();
          labelBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder getLabelBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLabelFieldBuilder().getBuilder();
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      public com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder getLabelOrBuilder() {
        if (labelBuilder_ != null) {
          return labelBuilder_.getMessageOrBuilder();
        } else {
          return label_ == null ?
              com.factset.protobuf.stach.table.ReferenceProto.Reference.getDefaultInstance() : label_;
        }
      }
      /**
       * <code>.factset.protobuf.stach.table.Reference label = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder> 
          getLabelFieldBuilder() {
        if (labelBuilder_ == null) {
          labelBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.factset.protobuf.stach.table.ReferenceProto.Reference, com.factset.protobuf.stach.table.ReferenceProto.Reference.Builder, com.factset.protobuf.stach.table.ReferenceProto.ReferenceOrBuilder>(
                  getLabel(),
                  getParentForChildren(),
                  isClean());
          label_ = null;
        }
        return labelBuilder_;
      }

      private com.google.protobuf.LazyStringArrayList series_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureSeriesIsMutable() {
        if (!series_.isModifiable()) {
          series_ = new com.google.protobuf.LazyStringArrayList(series_);
        }
        bitField0_ |= 0x00000008;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @return A list containing the series.
       */
      public com.google.protobuf.ProtocolStringList
          getSeriesList() {
        series_.makeImmutable();
        return series_;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @return The count of series.
       */
      public int getSeriesCount() {
        return series_.size();
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param index The index of the element to return.
       * @return The series at the given index.
       */
      public java.lang.String getSeries(int index) {
        return series_.get(index);
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param index The index of the value to return.
       * @return The bytes of the series at the given index.
       */
      public com.google.protobuf.ByteString
          getSeriesBytes(int index) {
        return series_.getByteString(index);
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param index The index to set the value at.
       * @param value The series to set.
       * @return This builder for chaining.
       */
      public Builder setSeries(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSeriesIsMutable();
        series_.set(index, value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param value The series to add.
       * @return This builder for chaining.
       */
      public Builder addSeries(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureSeriesIsMutable();
        series_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param values The series to add.
       * @return This builder for chaining.
       */
      public Builder addAllSeries(
          java.lang.Iterable<java.lang.String> values) {
        ensureSeriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, series_);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeries() {
        series_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string series = 4;</code>
       * @param value The bytes of the series to add.
       * @return This builder for chaining.
       */
      public Builder addSeriesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureSeriesIsMutable();
        series_.add(value);
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:factset.protobuf.stach.chart.Plot)
    }

    // @@protoc_insertion_point(class_scope:factset.protobuf.stach.chart.Plot)
    private static final com.factset.protobuf.stach.chart.PlotProto.Plot DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.factset.protobuf.stach.chart.PlotProto.Plot();
    }

    public static com.factset.protobuf.stach.chart.PlotProto.Plot getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Plot>
        PARSER = new com.google.protobuf.AbstractParser<Plot>() {
      @java.lang.Override
      public Plot parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Plot> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Plot> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.factset.protobuf.stach.chart.PlotProto.Plot getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Plot_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Plot_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#fds/protobuf/stach/chart/Plot.proto\022\034f" +
      "actset.protobuf.stach.chart\032\034google/prot" +
      "obuf/struct.proto\032(fds/protobuf/stach/ta" +
      "ble/Reference.proto\"\235\002\n\004Plot\022)\n\010template" +
      "\030\001 \001(\0132\027.google.protobuf.Struct\022F\n\nattri" +
      "butes\030\002 \003(\01322.factset.protobuf.stach.cha" +
      "rt.Plot.AttributesEntry\0226\n\005label\030\003 \001(\0132\'" +
      ".factset.protobuf.stach.table.Reference\022" +
      "\016\n\006series\030\004 \003(\t\032Z\n\017AttributesEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\0226\n\005value\030\002 \001(\0132\'.factset.protobu" +
      "f.stach.table.Reference:\0028\001BL\n com.facts" +
      "et.protobuf.stach.chartB\tPlotProto\252\002\034Fac" +
      "tSet.Protobuf.Stach.Chartb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.factset.protobuf.stach.table.ReferenceProto.getDescriptor(),
        });
    internal_static_factset_protobuf_stach_chart_Plot_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factset_protobuf_stach_chart_Plot_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Plot_descriptor,
        new java.lang.String[] { "Template", "Attributes", "Label", "Series", });
    internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_descriptor =
      internal_static_factset_protobuf_stach_chart_Plot_descriptor.getNestedTypes().get(0);
    internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_chart_Plot_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
    com.factset.protobuf.stach.table.ReferenceProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
