FROM maven:3.9.6-eclipse-temurin-17

LABEL org.label-schema.license="Apache-2.0" \
      org.label-schema.vcs-url="https://github.com/factset/stachschema-sdks" \
      org.label-schema.description="To generate Java Stach package" \
      maintainer="analytics.api.support@factset.com"

ENTRYPOINT ["bash", "/java/CI/generate-sdk.sh"]
