FROM maven:3.6.3-jdk-8

LABEL org.label-schema.license="Apache-2.0" \
      org.label-schema.vcs-url="https://github.com/factset/stachschema-sdks" \
      org.label-schema.description="To generate Java Stach package" \
      maintainer="analytics.api.support@factset.com"

COPY java /src

RUN /src/CI/build-sdk.sh

ENTRYPOINT ["bash", "/src/CI/extract-artifacts.sh"]