// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/v2/table/CellDefinition.proto

// Protobuf Java Version: 3.25.5
package com.factset.protobuf.stach.v2.table;

public final class CellDefinitionProto {
  private CellDefinitionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CellDefinitionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:factset.protobuf.stach.v2.table.CellDefinition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     * @return Whether the format field is set.
     */
    boolean hasFormat();
    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     * @return The format.
     */
    com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getFormat();
    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     */
    com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder getFormatOrBuilder();
  }
  /**
   * <pre>
   * A cell definition
   *
   * Overrides the column and row definition
   * </pre>
   *
   * Protobuf type {@code factset.protobuf.stach.v2.table.CellDefinition}
   */
  public static final class CellDefinition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:factset.protobuf.stach.v2.table.CellDefinition)
      CellDefinitionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CellDefinition.newBuilder() to construct.
    private CellDefinition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CellDefinition() {
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CellDefinition();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.factset.protobuf.stach.v2.table.CellDefinitionProto.internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.factset.protobuf.stach.v2.table.CellDefinitionProto.internal_static_factset_protobuf_stach_v2_table_CellDefinition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.class, com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object type_ = "";
    /**
     * <pre>
     * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
     * </pre>
     *
     * <code>string type = 1;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FORMAT_FIELD_NUMBER = 2;
    private com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat format_;
    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     * @return Whether the format field is set.
     */
    @java.lang.Override
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     * @return The format.
     */
    @java.lang.Override
    public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getFormat() {
      return format_ == null ? com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance() : format_;
    }
    /**
     * <pre>
     * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
     * </pre>
     *
     * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
     */
    @java.lang.Override
    public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder getFormatOrBuilder() {
      return format_ == null ? com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance() : format_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getFormat());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFormat());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition)) {
        return super.equals(obj);
      }
      com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition other = (com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition) obj;

      if (!getType()
          .equals(other.getType())) return false;
      if (hasFormat() != other.hasFormat()) return false;
      if (hasFormat()) {
        if (!getFormat()
            .equals(other.getFormat())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      if (hasFormat()) {
        hash = (37 * hash) + FORMAT_FIELD_NUMBER;
        hash = (53 * hash) + getFormat().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A cell definition
     *
     * Overrides the column and row definition
     * </pre>
     *
     * Protobuf type {@code factset.protobuf.stach.v2.table.CellDefinition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:factset.protobuf.stach.v2.table.CellDefinition)
        com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.factset.protobuf.stach.v2.table.CellDefinitionProto.internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.factset.protobuf.stach.v2.table.CellDefinitionProto.internal_static_factset_protobuf_stach_v2_table_CellDefinition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.class, com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.Builder.class);
      }

      // Construct using com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFormatFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = "";
        format_ = null;
        if (formatBuilder_ != null) {
          formatBuilder_.dispose();
          formatBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.factset.protobuf.stach.v2.table.CellDefinitionProto.internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition getDefaultInstanceForType() {
        return com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.getDefaultInstance();
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition build() {
        com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition buildPartial() {
        com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition result = new com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.format_ = formatBuilder_ == null
              ? format_
              : formatBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition) {
          return mergeFrom((com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition other) {
        if (other == com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasFormat()) {
          mergeFormat(other.getFormat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                type_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getFormatFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
       * </pre>
       *
       * <code>string type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        type_ = getDefaultInstance().getType();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data type; correlates with the chosen property for `ColumnData.data`; overrides the `ColumnDefinition.type`
       * </pre>
       *
       * <code>string type = 1;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat format_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder> formatBuilder_;
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       * @return Whether the format field is set.
       */
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       * @return The format.
       */
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat getFormat() {
        if (formatBuilder_ == null) {
          return format_ == null ? com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance() : format_;
        } else {
          return formatBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public Builder setFormat(com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat value) {
        if (formatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          format_ = value;
        } else {
          formatBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public Builder setFormat(
          com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder builderForValue) {
        if (formatBuilder_ == null) {
          format_ = builderForValue.build();
        } else {
          formatBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public Builder mergeFormat(com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat value) {
        if (formatBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            format_ != null &&
            format_ != com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance()) {
            getFormatBuilder().mergeFrom(value);
          } else {
            format_ = value;
          }
        } else {
          formatBuilder_.mergeFrom(value);
        }
        if (format_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        format_ = null;
        if (formatBuilder_ != null) {
          formatBuilder_.dispose();
          formatBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder getFormatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getFormatFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      public com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder getFormatOrBuilder() {
        if (formatBuilder_ != null) {
          return formatBuilder_.getMessageOrBuilder();
        } else {
          return format_ == null ?
              com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.getDefaultInstance() : format_;
        }
      }
      /**
       * <pre>
       * The data format; overrides the `RowDefinition.format` and the `ColumnDefinition.format`
       * </pre>
       *
       * <code>.factset.protobuf.stach.v2.table.DataFormat format = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder> 
          getFormatFieldBuilder() {
        if (formatBuilder_ == null) {
          formatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormat.Builder, com.factset.protobuf.stach.v2.table.DataFormatProto.DataFormatOrBuilder>(
                  getFormat(),
                  getParentForChildren(),
                  isClean());
          format_ = null;
        }
        return formatBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:factset.protobuf.stach.v2.table.CellDefinition)
    }

    // @@protoc_insertion_point(class_scope:factset.protobuf.stach.v2.table.CellDefinition)
    private static final com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition();
    }

    public static com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CellDefinition>
        PARSER = new com.google.protobuf.AbstractParser<CellDefinition>() {
      @java.lang.Override
      public CellDefinition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CellDefinition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CellDefinition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.factset.protobuf.stach.v2.table.CellDefinitionProto.CellDefinition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_factset_protobuf_stach_v2_table_CellDefinition_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n0fds/protobuf/stach/v2/table/CellDefini" +
      "tion.proto\022\037factset.protobuf.stach.v2.ta" +
      "ble\032,fds/protobuf/stach/v2/table/DataFor" +
      "mat.proto\"[\n\016CellDefinition\022\014\n\004type\030\001 \001(" +
      "\t\022;\n\006format\030\002 \001(\0132+.factset.protobuf.sta" +
      "ch.v2.table.DataFormatB\240\001\n#com.factset.p" +
      "rotobuf.stach.v2.tableB\023CellDefinitionPr" +
      "otoZBgithub.com/factset/stachschema-sdks" +
      "/go/fds/protobuf/stach/v2/table\252\002\037FactSe" +
      "t.Protobuf.Stach.V2.Tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.factset.protobuf.stach.v2.table.DataFormatProto.getDescriptor(),
        });
    internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_factset_protobuf_stach_v2_table_CellDefinition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_factset_protobuf_stach_v2_table_CellDefinition_descriptor,
        new java.lang.String[] { "Type", "Format", });
    com.factset.protobuf.stach.v2.table.DataFormatProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
