// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fds/protobuf/stach/v2/table/HorizontalAlignment.proto

// Protobuf Java Version: 3.25.5
package com.factset.protobuf.stach.v2.table;

public final class HorizontalAlignmentProto {
  private HorizontalAlignmentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * A horizontal alignment
   * </pre>
   *
   * Protobuf enum {@code factset.protobuf.stach.v2.table.HorizontalAlignment}
   */
  public enum HorizontalAlignment
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * This value should never be used, but exists to ensure that a value is specified
     * </pre>
     *
     * <code>UNKNOWN_HALIGN = 0;</code>
     */
    UNKNOWN_HALIGN(0),
    /**
     * <pre>
     * Value is horizontally aligned to the left of the cell
     * </pre>
     *
     * <code>LEFT = 1;</code>
     */
    LEFT(1),
    /**
     * <pre>
     * Value is horizontally aligned in the center of the cell
     * </pre>
     *
     * <code>CENTER = 2;</code>
     */
    CENTER(2),
    /**
     * <pre>
     * Value is horizontally aligned to the right of the cell
     * </pre>
     *
     * <code>RIGHT = 3;</code>
     */
    RIGHT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * This value should never be used, but exists to ensure that a value is specified
     * </pre>
     *
     * <code>UNKNOWN_HALIGN = 0;</code>
     */
    public static final int UNKNOWN_HALIGN_VALUE = 0;
    /**
     * <pre>
     * Value is horizontally aligned to the left of the cell
     * </pre>
     *
     * <code>LEFT = 1;</code>
     */
    public static final int LEFT_VALUE = 1;
    /**
     * <pre>
     * Value is horizontally aligned in the center of the cell
     * </pre>
     *
     * <code>CENTER = 2;</code>
     */
    public static final int CENTER_VALUE = 2;
    /**
     * <pre>
     * Value is horizontally aligned to the right of the cell
     * </pre>
     *
     * <code>RIGHT = 3;</code>
     */
    public static final int RIGHT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static HorizontalAlignment valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static HorizontalAlignment forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_HALIGN;
        case 1: return LEFT;
        case 2: return CENTER;
        case 3: return RIGHT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HorizontalAlignment>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        HorizontalAlignment> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HorizontalAlignment>() {
            public HorizontalAlignment findValueByNumber(int number) {
              return HorizontalAlignment.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.factset.protobuf.stach.v2.table.HorizontalAlignmentProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final HorizontalAlignment[] VALUES = values();

    public static HorizontalAlignment valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private HorizontalAlignment(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:factset.protobuf.stach.v2.table.HorizontalAlignment)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5fds/protobuf/stach/v2/table/Horizontal" +
      "Alignment.proto\022\037factset.protobuf.stach." +
      "v2.table*J\n\023HorizontalAlignment\022\022\n\016UNKNO" +
      "WN_HALIGN\020\000\022\010\n\004LEFT\020\001\022\n\n\006CENTER\020\002\022\t\n\005RIG" +
      "HT\020\003B\245\001\n#com.factset.protobuf.stach.v2.t" +
      "ableB\030HorizontalAlignmentProtoZBgithub.c" +
      "om/factset/stachschema-sdks/go/fds/proto" +
      "buf/stach/v2/table\252\002\037FactSet.Protobuf.St" +
      "ach.V2.Tableb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
