FROM golang:1.21

LABEL org.label-schema.license="Apache-2.0" \
      org.label-schema.vcs-url="https://github.com/factset/stachschema-sdks" \
      org.label-schema.description="To build Go Stach package" \
      maintainer="analytics.api.support@factset.com"

COPY go /src

RUN /src/CI/build-sdk.sh
