# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/v2/table/ColumnDefinition.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/v2/table/ColumnDefinition.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.v2.table import DataFormat_pb2 as fds_dot_protobuf_dot_stach_dot_v2_dot_table_dot_DataFormat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2fds/protobuf/stach/v2/table/ColumnDefinition.proto\x12\x1f\x66\x61\x63tset.protobuf.stach.v2.table\x1a,fds/protobuf/stach/v2/table/DataFormat.proto\"\xf4\x01\n\x10\x43olumnDefinition\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x14\n\x0cis_dimension\x18\x05 \x01(\x08\x12\x11\n\tis_hidden\x18\x06 \x01(\x08\x12\x17\n\x0fnext_sibling_id\x18\x07 \x01(\t\x12\x11\n\tparent_id\x18\x08 \x01(\t\x12\x11\n\theader_id\x18\t \x01(\t\x12;\n\x06\x66ormat\x18\n \x01(\x0b\x32+.factset.protobuf.stach.v2.table.DataFormatB\xa2\x01\n#com.factset.protobuf.stach.v2.tableB\x15\x43olumnDefinitionProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\xaa\x02\x1f\x46\x61\x63tSet.Protobuf.Stach.V2.Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.v2.table.ColumnDefinition_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.factset.protobuf.stach.v2.tableB\025ColumnDefinitionProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\252\002\037FactSet.Protobuf.Stach.V2.Table'
  _globals['_COLUMNDEFINITION']._serialized_start=134
  _globals['_COLUMNDEFINITION']._serialized_end=378
# @@protoc_insertion_point(module_scope)
