# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/v2/table/ListOfMetadata.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/v2/table/ListOfMetadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0fds/protobuf/stach/v2/table/ListOfMetadata.proto\x12\x1f\x66\x61\x63tset.protobuf.stach.v2.table\"\x1d\n\x0eListOfMetadata\x12\x0b\n\x03ids\x18\x01 \x03(\tB\xa0\x01\n#com.factset.protobuf.stach.v2.tableB\x13ListOfMetadataProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\xaa\x02\x1f\x46\x61\x63tSet.Protobuf.Stach.V2.Tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.v2.table.ListOfMetadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.factset.protobuf.stach.v2.tableB\023ListOfMetadataProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\252\002\037FactSet.Protobuf.Stach.V2.Table'
  _globals['_LISTOFMETADATA']._serialized_start=85
  _globals['_LISTOFMETADATA']._serialized_end=114
# @@protoc_insertion_point(module_scope)
