# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fds/protobuf/stach/Package.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'fds/protobuf/stach/Package.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.table import Table_pb2 as fds_dot_protobuf_dot_stach_dot_table_dot_Table__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n fds/protobuf/stach/Package.proto\x12\x16\x66\x61\x63tset.protobuf.stach\x1a$fds/protobuf/stach/table/Table.proto\"\xc6\x01\n\x07Package\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x19\n\x11primary_table_ids\x18\x02 \x03(\t\x12;\n\x06tables\x18\x03 \x03(\x0b\x32+.factset.protobuf.stach.Package.TablesEntry\x1aR\n\x0bTablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.factset.protobuf.stach.table.Table:\x02\x38\x01\x42\x43\n\x1a\x63om.factset.protobuf.stachB\x0cPackageProto\xaa\x02\x16\x46\x61\x63tSet.Protobuf.Stachb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fds.protobuf.stach.Package_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.factset.protobuf.stachB\014PackageProto\252\002\026FactSet.Protobuf.Stach'
  _globals['_PACKAGE_TABLESENTRY']._loaded_options = None
  _globals['_PACKAGE_TABLESENTRY']._serialized_options = b'8\001'
  _globals['_PACKAGE']._serialized_start=99
  _globals['_PACKAGE']._serialized_end=297
  _globals['_PACKAGE_TABLESENTRY']._serialized_start=215
  _globals['_PACKAGE_TABLESENTRY']._serialized_end=297
# @@protoc_insertion_point(module_scope)
