# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fds/protobuf/stach/v2/table/RowDefinition.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fds.protobuf.stach.v2.table import DataFormat_pb2 as fds_dot_protobuf_dot_stach_dot_v2_dot_table_dot_DataFormat__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fds/protobuf/stach/v2/table/RowDefinition.proto',
  package='factset.protobuf.stach.v2.table',
  syntax='proto3',
  serialized_options=b'\n#com.factset.protobuf.stach.v2.tableB\022RowDefinitionProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\252\002\037FactSet.Protobuf.Stach.V2.Table',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n/fds/protobuf/stach/v2/table/RowDefinition.proto\x12\x1f\x66\x61\x63tset.protobuf.stach.v2.table\x1a,fds/protobuf/stach/v2/table/DataFormat.proto\"X\n\rRowDefinition\x12\n\n\x02id\x18\x01 \x01(\t\x12;\n\x06\x66ormat\x18\x02 \x01(\x0b\x32+.factset.protobuf.stach.v2.table.DataFormatB\x9f\x01\n#com.factset.protobuf.stach.v2.tableB\x12RowDefinitionProtoZBgithub.com/factset/stachschema-sdks/go/fds/protobuf/stach/v2/table\xaa\x02\x1f\x46\x61\x63tSet.Protobuf.Stach.V2.Tableb\x06proto3'
  ,
  dependencies=[fds_dot_protobuf_dot_stach_dot_v2_dot_table_dot_DataFormat__pb2.DESCRIPTOR,])




_ROWDEFINITION = _descriptor.Descriptor(
  name='RowDefinition',
  full_name='factset.protobuf.stach.v2.table.RowDefinition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='factset.protobuf.stach.v2.table.RowDefinition.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='format', full_name='factset.protobuf.stach.v2.table.RowDefinition.format', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=218,
)

_ROWDEFINITION.fields_by_name['format'].message_type = fds_dot_protobuf_dot_stach_dot_v2_dot_table_dot_DataFormat__pb2._DATAFORMAT
DESCRIPTOR.message_types_by_name['RowDefinition'] = _ROWDEFINITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RowDefinition = _reflection.GeneratedProtocolMessageType('RowDefinition', (_message.Message,), {
  'DESCRIPTOR' : _ROWDEFINITION,
  '__module__' : 'fds.protobuf.stach.v2.table.RowDefinition_pb2'
  # @@protoc_insertion_point(class_scope:factset.protobuf.stach.v2.table.RowDefinition)
  })
_sym_db.RegisterMessage(RowDefinition)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
